// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation £®1.1.2_01£¨±‡“Î∞Ê R40£©
// Generated source version: 1.1.2

package com.amalto.core.webservice;


public class WSRoleSpecification {
    protected java.lang.String objectType;
    protected boolean admin;
    protected com.amalto.core.webservice.WSRoleSpecificationInstance[] instance;
    
    public WSRoleSpecification() {
    }
    
    public WSRoleSpecification(java.lang.String objectType, boolean admin, com.amalto.core.webservice.WSRoleSpecificationInstance[] instance) {
        this.objectType = objectType;
        this.admin = admin;
        this.instance = instance;
    }
    
    public java.lang.String getObjectType() {
        return objectType;
    }
    
    public void setObjectType(java.lang.String objectType) {
        this.objectType = objectType;
    }
    
    public boolean isAdmin() {
        return admin;
    }
    
    public void setAdmin(boolean admin) {
        this.admin = admin;
    }
    
    public com.amalto.core.webservice.WSRoleSpecificationInstance[] getInstance() {
        return instance;
    }
    
    public void setInstance(com.amalto.core.webservice.WSRoleSpecificationInstance[] instance) {
        this.instance = instance;
    }
}
