// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.2_01, construire R40)
// Generated source version: 1.1.2

package com.amalto.core.webservice;


public class WSSynchronizationPlanIDsArray {
    protected com.amalto.core.webservice.WSSynchronizationPlanIDs[] wsSynchronizationPlanIDs;
    
    public WSSynchronizationPlanIDsArray() {
    }
    
    public WSSynchronizationPlanIDsArray(com.amalto.core.webservice.WSSynchronizationPlanIDs[] wsSynchronizationPlanIDs) {
        this.wsSynchronizationPlanIDs = wsSynchronizationPlanIDs;
    }
    
    public com.amalto.core.webservice.WSSynchronizationPlanIDs[] getWsSynchronizationPlanIDs() {
        return wsSynchronizationPlanIDs;
    }
    
    public void setWsSynchronizationPlanIDs(com.amalto.core.webservice.WSSynchronizationPlanIDs[] wsSynchronizationPlanIDs) {
        this.wsSynchronizationPlanIDs = wsSynchronizationPlanIDs;
    }
}
