// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation £®1.1.2_01£¨±‡“Î∞Ê R40£©
// Generated source version: 1.1.2

package com.amalto.core.webservice;


public class WSUniverseItemsRevisionIDs {
    protected java.lang.String conceptPattern;
    protected java.lang.String revisionID;
    
    public WSUniverseItemsRevisionIDs() {
    }
    
    public WSUniverseItemsRevisionIDs(java.lang.String conceptPattern, java.lang.String revisionID) {
        this.conceptPattern = conceptPattern;
        this.revisionID = revisionID;
    }
    
    public java.lang.String getConceptPattern() {
        return conceptPattern;
    }
    
    public void setConceptPattern(java.lang.String conceptPattern) {
        this.conceptPattern = conceptPattern;
    }
    
    public java.lang.String getRevisionID() {
        return revisionID;
    }
    
    public void setRevisionID(java.lang.String revisionID) {
        this.revisionID = revisionID;
    }
}
