// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation £®1.1.2_01£¨±‡“Î∞Ê R40£©
// Generated source version: 1.1.2

package com.amalto.core.webservice;


public class WSExecuteTransformerV2 {
    protected com.amalto.core.webservice.WSTransformerContext wsTransformerContext;
    protected com.amalto.core.webservice.WSTypedContent wsTypedContent;
    
    public WSExecuteTransformerV2() {
    }
    
    public WSExecuteTransformerV2(com.amalto.core.webservice.WSTransformerContext wsTransformerContext, com.amalto.core.webservice.WSTypedContent wsTypedContent) {
        this.wsTransformerContext = wsTransformerContext;
        this.wsTypedContent = wsTypedContent;
    }
    
    public com.amalto.core.webservice.WSTransformerContext getWsTransformerContext() {
        return wsTransformerContext;
    }
    
    public void setWsTransformerContext(com.amalto.core.webservice.WSTransformerContext wsTransformerContext) {
        this.wsTransformerContext = wsTransformerContext;
    }
    
    public com.amalto.core.webservice.WSTypedContent getWsTypedContent() {
        return wsTypedContent;
    }
    
    public void setWsTypedContent(com.amalto.core.webservice.WSTypedContent wsTypedContent) {
        this.wsTypedContent = wsTypedContent;
    }
}
