// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation £®1.1.2_01£¨±‡“Î∞Ê R40£©
// Generated source version: 1.1.2

package com.amalto.core.webservice;


public class WSGetObjectsForSynchronizationPlans {
    protected java.lang.String[] regex;
    
    public WSGetObjectsForSynchronizationPlans() {
    }
    
    public WSGetObjectsForSynchronizationPlans(java.lang.String[] regex) {
        this.regex = regex;
    }
    
    public java.lang.String[] getRegex() {
        return regex;
    }
    
    public void setRegex(java.lang.String[] regex) {
        this.regex = regex;
    }
}
