// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation £®1.1.2_01£¨±‡“Î∞Ê R40£©
// Generated source version: 1.1.2

package com.amalto.core.webservice;


public class WSGetComponentVersion {
    protected com.amalto.core.webservice.WSComponent component;
    protected java.lang.String id;
    
    public WSGetComponentVersion() {
    }
    
    public WSGetComponentVersion(com.amalto.core.webservice.WSComponent component, java.lang.String id) {
        this.component = component;
        this.id = id;
    }
    
    public com.amalto.core.webservice.WSComponent getComponent() {
        return component;
    }
    
    public void setComponent(com.amalto.core.webservice.WSComponent component) {
        this.component = component;
    }
    
    public java.lang.String getId() {
        return id;
    }
    
    public void setId(java.lang.String id) {
        this.id = id;
    }
}
