// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation £®1.1.2_01£¨±‡“Î∞Ê R40£©
// Generated source version: 1.1.2

package com.amalto.core.webservice;


public class WSPutDataCluster {
    protected com.amalto.core.webservice.WSDataCluster wsDataCluster;
    
    public WSPutDataCluster() {
    }
    
    public WSPutDataCluster(com.amalto.core.webservice.WSDataCluster wsDataCluster) {
        this.wsDataCluster = wsDataCluster;
    }
    
    public com.amalto.core.webservice.WSDataCluster getWsDataCluster() {
        return wsDataCluster;
    }
    
    public void setWsDataCluster(com.amalto.core.webservice.WSDataCluster wsDataCluster) {
        this.wsDataCluster = wsDataCluster;
    }
}
