// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation £®1.1.2_01£¨±‡“Î∞Ê R40£©
// Generated source version: 1.1.2

package com.amalto.core.webservice;


public class WSPutVersioningSystemConfiguration {
    protected com.amalto.core.webservice.WSVersioningSystemConfiguration versioningSystemConfiguration;
    
    public WSPutVersioningSystemConfiguration() {
    }
    
    public WSPutVersioningSystemConfiguration(com.amalto.core.webservice.WSVersioningSystemConfiguration versioningSystemConfiguration) {
        this.versioningSystemConfiguration = versioningSystemConfiguration;
    }
    
    public com.amalto.core.webservice.WSVersioningSystemConfiguration getVersioningSystemConfiguration() {
        return versioningSystemConfiguration;
    }
    
    public void setVersioningSystemConfiguration(com.amalto.core.webservice.WSVersioningSystemConfiguration versioningSystemConfiguration) {
        this.versioningSystemConfiguration = versioningSystemConfiguration;
    }
}
