// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation £®1.1.2_01£¨±‡“Î∞Ê R40£©
// Generated source version: 1.1.2

package com.amalto.core.webservice;


public class WSResolveSynchronizationItem {
    protected com.amalto.core.webservice.WSSynchronizationItemPK wsSynchronizationItemPK;
    protected java.lang.String newProjection;
    
    public WSResolveSynchronizationItem() {
    }
    
    public WSResolveSynchronizationItem(com.amalto.core.webservice.WSSynchronizationItemPK wsSynchronizationItemPK, java.lang.String newProjection) {
        this.wsSynchronizationItemPK = wsSynchronizationItemPK;
        this.newProjection = newProjection;
    }
    
    public com.amalto.core.webservice.WSSynchronizationItemPK getWsSynchronizationItemPK() {
        return wsSynchronizationItemPK;
    }
    
    public void setWsSynchronizationItemPK(com.amalto.core.webservice.WSSynchronizationItemPK wsSynchronizationItemPK) {
        this.wsSynchronizationItemPK = wsSynchronizationItemPK;
    }
    
    public java.lang.String getNewProjection() {
        return newProjection;
    }
    
    public void setNewProjection(java.lang.String newProjection) {
        this.newProjection = newProjection;
    }
}
