// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation £®1.1.2_01£¨±‡“Î∞Ê R40£©
// Generated source version: 1.1.2

package com.amalto.core.webservice;


public class WSRoutingRulePKArray {
    protected com.amalto.core.webservice.WSRoutingRulePK[] wsRoutingRulePKs;
    
    public WSRoutingRulePKArray() {
    }
    
    public WSRoutingRulePKArray(com.amalto.core.webservice.WSRoutingRulePK[] wsRoutingRulePKs) {
        this.wsRoutingRulePKs = wsRoutingRulePKs;
    }
    
    public com.amalto.core.webservice.WSRoutingRulePK[] getWsRoutingRulePKs() {
        return wsRoutingRulePKs;
    }
    
    public void setWsRoutingRulePKs(com.amalto.core.webservice.WSRoutingRulePK[] wsRoutingRulePKs) {
        this.wsRoutingRulePKs = wsRoutingRulePKs;
    }
}
