// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation £®1.1.2_01£¨±‡“Î∞Ê R40£©
// Generated source version: 1.1.2

package com.amalto.core.webservice;


public class WSServicesList {
    protected com.amalto.core.webservice.WSServicesListItem[] item;
    
    public WSServicesList() {
    }
    
    public WSServicesList(com.amalto.core.webservice.WSServicesListItem[] item) {
        this.item = item;
    }
    
    public com.amalto.core.webservice.WSServicesListItem[] getItem() {
        return item;
    }
    
    public void setItem(com.amalto.core.webservice.WSServicesListItem[] item) {
        this.item = item;
    }
}
