// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation £®1.1.2_01£¨±‡“Î∞Ê R40£©
// Generated source version: 1.1.2

package com.amalto.core.webservice;


public class WSSynchronizationItemPK {
    protected java.lang.String[] ids;
    
    public WSSynchronizationItemPK() {
    }
    
    public WSSynchronizationItemPK(java.lang.String[] ids) {
        this.ids = ids;
    }
    
    public java.lang.String[] getIds() {
        return ids;
    }
    
    public void setIds(java.lang.String[] ids) {
        this.ids = ids;
    }
}
