// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation £®1.1.2_01£¨±‡“Î∞Ê R40£©
// Generated source version: 1.1.2

package com.amalto.core.webservice;


public class WSTransformerContextProjectedItemPKs {
    protected com.amalto.core.webservice.WSItemPK[] wsItemPOJOPK;
    
    public WSTransformerContextProjectedItemPKs() {
    }
    
    public WSTransformerContextProjectedItemPKs(com.amalto.core.webservice.WSItemPK[] wsItemPOJOPK) {
        this.wsItemPOJOPK = wsItemPOJOPK;
    }
    
    public com.amalto.core.webservice.WSItemPK[] getWsItemPOJOPK() {
        return wsItemPOJOPK;
    }
    
    public void setWsItemPOJOPK(com.amalto.core.webservice.WSItemPK[] wsItemPOJOPK) {
        this.wsItemPOJOPK = wsItemPOJOPK;
    }
}
