// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation £®1.1.2_01£¨±‡“Î∞Ê R40£©
// Generated source version: 1.1.2

package com.amalto.core.webservice;


public class WSVersioningUniverseVersions {
    protected com.amalto.core.webservice.WSVersioningUniverseVersionsTagStructure[] tagStructure;
    
    public WSVersioningUniverseVersions() {
    }
    
    public WSVersioningUniverseVersions(com.amalto.core.webservice.WSVersioningUniverseVersionsTagStructure[] tagStructure) {
        this.tagStructure = tagStructure;
    }
    
    public com.amalto.core.webservice.WSVersioningUniverseVersionsTagStructure[] getTagStructure() {
        return tagStructure;
    }
    
    public void setTagStructure(com.amalto.core.webservice.WSVersioningUniverseVersionsTagStructure[] tagStructure) {
        this.tagStructure = tagStructure;
    }
}
