/*
 * Generated by XDoclet - Do not edit!
 */
package com.amalto.core.objects.datamodel.ejb.remote;

/**
 * Home interface for DataModelCtrl.
 * @xdoclet-generated at 7-09-09
 * @copyright The XDoclet Team
 * @author XDoclet
 * @version ${version}
 */
public interface DataModelCtrlHome
   extends javax.ejb.EJBHome
{
   public static final String COMP_NAME="java:comp/env/ejb/DataModelCtrl";
   public static final String JNDI_NAME="amalto/remote/core/datamodelctrl";

   public com.amalto.core.objects.datamodel.ejb.remote.DataModelCtrl create()
      throws javax.ejb.CreateException,java.rmi.RemoteException;

}
