/*
 * Generated by XDoclet - Do not edit!
 */
package com.amalto.core.plugin.base.workflowtrigger.ejb.local;

/**
 * Local home interface for WorkflowTriggerPluginBean.
 * @xdoclet-generated at 20-11-09
 * @copyright The XDoclet Team
 * @author XDoclet
 * @version ${version}
 */
public interface WorkflowTriggerPluginBeanLocalHome
   extends javax.ejb.EJBLocalHome
{
   public static final String COMP_NAME="java:comp/env/ejb/WorkflowTriggerPluginBeanLocal";
   public static final String JNDI_NAME="amalto/local/transformer/plugin/workflowtrigger";

   public com.amalto.core.plugin.base.workflowtrigger.ejb.local.WorkflowTriggerPluginBeanLocal create()
      throws javax.ejb.CreateException;

}
