/*
 * Generated by XDoclet - Do not edit!
 */
package com.amalto.core.objects.transformers.v2.ejb.remote;

/**
 * Home interface for TransformerV2Ctrl.
 * @xdoclet-generated
 * @copyright The XDoclet Team
 * @author XDoclet
 * @version ${version}
 */
public interface TransformerV2CtrlHome
   extends javax.ejb.EJBHome
{
   public static final String COMP_NAME="java:comp/env/ejb/TransformerV2Ctrl";
   public static final String JNDI_NAME="amalto/remote/core/transformerv2ctrl";

   public com.amalto.core.objects.transformers.v2.ejb.remote.TransformerV2Ctrl create()
      throws javax.ejb.CreateException,java.rmi.RemoteException;

}
