/*
 * Generated by XDoclet - Do not edit!
 */
package com.amalto.core.plugin.base.regexp.ejb.local;

/**
 * Local home interface for RegexpTransformerPlugin.
 * @xdoclet-generated at 18-11-09
 * @copyright The XDoclet Team
 * @author XDoclet
 * @version ${version}
 */
public interface RegexpTransformerPluginLocalHome
   extends javax.ejb.EJBLocalHome
{
   public static final String COMP_NAME="java:comp/env/ejb/RegexpTransformerPluginLocal";
   public static final String JNDI_NAME="amalto/local/transformer/plugin/regexp";

   public com.amalto.core.plugin.base.regexp.ejb.local.RegexpTransformerPluginLocal create()
      throws javax.ejb.CreateException;

}
