// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation £®1.1.2_01£¨±‡“Î∞Ê R40£©
// Generated source version: 1.1.2

package com.amalto.core.webservice;


public class WSBackgroundJobPKArray {
    protected com.amalto.core.webservice.WSBackgroundJobPK[] wsBackgroundJobPK;
    
    public WSBackgroundJobPKArray() {
    }
    
    public WSBackgroundJobPKArray(com.amalto.core.webservice.WSBackgroundJobPK[] wsBackgroundJobPK) {
        this.wsBackgroundJobPK = wsBackgroundJobPK;
    }
    
    public com.amalto.core.webservice.WSBackgroundJobPK[] getWsBackgroundJobPK() {
        return wsBackgroundJobPK;
    }
    
    public void setWsBackgroundJobPK(com.amalto.core.webservice.WSBackgroundJobPK[] wsBackgroundJobPK) {
        this.wsBackgroundJobPK = wsBackgroundJobPK;
    }
}
