// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation £®1.1.2_01£¨±‡“Î∞Ê R40£©
// Generated source version: 1.1.2

package com.amalto.core.webservice;


public class WSDeleteSynchronizationPlan {
    protected com.amalto.core.webservice.WSSynchronizationPlanPK wsSynchronizationPlanPK;
    
    public WSDeleteSynchronizationPlan() {
    }
    
    public WSDeleteSynchronizationPlan(com.amalto.core.webservice.WSSynchronizationPlanPK wsSynchronizationPlanPK) {
        this.wsSynchronizationPlanPK = wsSynchronizationPlanPK;
    }
    
    public com.amalto.core.webservice.WSSynchronizationPlanPK getWsSynchronizationPlanPK() {
        return wsSynchronizationPlanPK;
    }
    
    public void setWsSynchronizationPlanPK(com.amalto.core.webservice.WSSynchronizationPlanPK wsSynchronizationPlanPK) {
        this.wsSynchronizationPlanPK = wsSynchronizationPlanPK;
    }
}
