// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation £®1.1.2_01£¨±‡“Î∞Ê R40£©
// Generated source version: 1.1.2

package com.amalto.core.webservice;


public class WSDeleteTransformerV2 {
    protected com.amalto.core.webservice.WSTransformerV2PK wsTransformerV2PK;
    
    public WSDeleteTransformerV2() {
    }
    
    public WSDeleteTransformerV2(com.amalto.core.webservice.WSTransformerV2PK wsTransformerV2PK) {
        this.wsTransformerV2PK = wsTransformerV2PK;
    }
    
    public com.amalto.core.webservice.WSTransformerV2PK getWsTransformerV2PK() {
        return wsTransformerV2PK;
    }
    
    public void setWsTransformerV2PK(com.amalto.core.webservice.WSTransformerV2PK wsTransformerV2PK) {
        this.wsTransformerV2PK = wsTransformerV2PK;
    }
}
