// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.2_01, construire R40)
// Generated source version: 1.1.2

package com.amalto.core.webservice;


public class WSDirectQuery {
    protected com.amalto.core.webservice.WSDataClusterPK wsDataClusterPK;
    protected java.lang.String query;
    
    public WSDirectQuery() {
    }
    
    public WSDirectQuery(com.amalto.core.webservice.WSDataClusterPK wsDataClusterPK, java.lang.String query) {
        this.wsDataClusterPK = wsDataClusterPK;
        this.query = query;
    }
    
    public com.amalto.core.webservice.WSDataClusterPK getWsDataClusterPK() {
        return wsDataClusterPK;
    }
    
    public void setWsDataClusterPK(com.amalto.core.webservice.WSDataClusterPK wsDataClusterPK) {
        this.wsDataClusterPK = wsDataClusterPK;
    }
    
    public java.lang.String getQuery() {
        return query;
    }
    
    public void setQuery(java.lang.String query) {
        this.query = query;
    }
}
