// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation £®1.1.2_01£¨±‡“Î∞Ê R40£©
// Generated source version: 1.1.2

package com.amalto.core.webservice;


public class WSGetTransformerPluginV2SList {
    protected java.lang.String language;
    
    public WSGetTransformerPluginV2SList() {
    }
    
    public WSGetTransformerPluginV2SList(java.lang.String language) {
        this.language = language;
    }
    
    public java.lang.String getLanguage() {
        return language;
    }
    
    public void setLanguage(java.lang.String language) {
        this.language = language;
    }
}
