// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation £®1.1.2_01£¨±‡“Î∞Ê R40£©
// Generated source version: 1.1.2

package com.amalto.core.webservice;


public class WSGetRoutingOrderV2SByCriteria {
    protected com.amalto.core.webservice.WSRoutingOrderV2SearchCriteria wsSearchCriteria;
    
    public WSGetRoutingOrderV2SByCriteria() {
    }
    
    public WSGetRoutingOrderV2SByCriteria(com.amalto.core.webservice.WSRoutingOrderV2SearchCriteria wsSearchCriteria) {
        this.wsSearchCriteria = wsSearchCriteria;
    }
    
    public com.amalto.core.webservice.WSRoutingOrderV2SearchCriteria getWsSearchCriteria() {
        return wsSearchCriteria;
    }
    
    public void setWsSearchCriteria(com.amalto.core.webservice.WSRoutingOrderV2SearchCriteria wsSearchCriteria) {
        this.wsSearchCriteria = wsSearchCriteria;
    }
}
