// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation £®1.1.2_01£¨±‡“Î∞Ê R40£©
// Generated source version: 1.1.2

package com.amalto.core.webservice;


public class WSLinkedHashMap {
    protected com.amalto.core.webservice.WSGetItemsPivotIndexPivotWithKeysTypedContentEntry[] typedContentEntry;
    
    public WSLinkedHashMap() {
    }
    
    public WSLinkedHashMap(com.amalto.core.webservice.WSGetItemsPivotIndexPivotWithKeysTypedContentEntry[] typedContentEntry) {
        this.typedContentEntry = typedContentEntry;
    }
    
    public com.amalto.core.webservice.WSGetItemsPivotIndexPivotWithKeysTypedContentEntry[] getTypedContentEntry() {
        return typedContentEntry;
    }
    
    public void setTypedContentEntry(com.amalto.core.webservice.WSGetItemsPivotIndexPivotWithKeysTypedContentEntry[] typedContentEntry) {
        this.typedContentEntry = typedContentEntry;
    }
}
