// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation £®1.1.2_01£¨±‡“Î∞Ê R40£©
// Generated source version: 1.1.2

package com.amalto.core.webservice;


public class WSPing {
    protected java.lang.String echo;
    
    public WSPing() {
    }
    
    public WSPing(java.lang.String echo) {
        this.echo = echo;
    }
    
    public java.lang.String getEcho() {
        return echo;
    }
    
    public void setEcho(java.lang.String echo) {
        this.echo = echo;
    }
}
