// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation £®1.1.2_01£¨±‡“Î∞Ê R40£©
// Generated source version: 1.1.2

package com.amalto.core.webservice;


public class WSPutMenu {
    protected com.amalto.core.webservice.WSMenu wsMenu;
    
    public WSPutMenu() {
    }
    
    public WSPutMenu(com.amalto.core.webservice.WSMenu wsMenu) {
        this.wsMenu = wsMenu;
    }
    
    public com.amalto.core.webservice.WSMenu getWsMenu() {
        return wsMenu;
    }
    
    public void setWsMenu(com.amalto.core.webservice.WSMenu wsMenu) {
        this.wsMenu = wsMenu;
    }
}
