// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation £®1.1.2_01£¨±‡“Î∞Ê R40£©
// Generated source version: 1.1.2

package com.amalto.core.webservice;


public class WSPutBackgroundJob {
    protected com.amalto.core.webservice.WSBackgroundJob wsBackgroundJob;
    
    public WSPutBackgroundJob() {
    }
    
    public WSPutBackgroundJob(com.amalto.core.webservice.WSBackgroundJob wsBackgroundJob) {
        this.wsBackgroundJob = wsBackgroundJob;
    }
    
    public com.amalto.core.webservice.WSBackgroundJob getWsBackgroundJob() {
        return wsBackgroundJob;
    }
    
    public void setWsBackgroundJob(com.amalto.core.webservice.WSBackgroundJob wsBackgroundJob) {
        this.wsBackgroundJob = wsBackgroundJob;
    }
}
