// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation £®1.1.2_01£¨±‡“Î∞Ê R40£©
// Generated source version: 1.1.2

package com.amalto.core.webservice;


public class WSPutView {
    protected com.amalto.core.webservice.WSView wsView;
    
    public WSPutView() {
    }
    
    public WSPutView(com.amalto.core.webservice.WSView wsView) {
        this.wsView = wsView;
    }
    
    public com.amalto.core.webservice.WSView getWsView() {
        return wsView;
    }
    
    public void setWsView(com.amalto.core.webservice.WSView wsView) {
        this.wsView = wsView;
    }
}
