// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation £®1.1.2_01£¨±‡“Î∞Ê R40£©
// Generated source version: 1.1.2

package com.amalto.core.webservice;


public class WSPutSynchronizationItem {
    protected com.amalto.core.webservice.WSSynchronizationItem wsSynchronizationItem;
    
    public WSPutSynchronizationItem() {
    }
    
    public WSPutSynchronizationItem(com.amalto.core.webservice.WSSynchronizationItem wsSynchronizationItem) {
        this.wsSynchronizationItem = wsSynchronizationItem;
    }
    
    public com.amalto.core.webservice.WSSynchronizationItem getWsSynchronizationItem() {
        return wsSynchronizationItem;
    }
    
    public void setWsSynchronizationItem(com.amalto.core.webservice.WSSynchronizationItem wsSynchronizationItem) {
        this.wsSynchronizationItem = wsSynchronizationItem;
    }
}
