// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation £®1.1.2_01£¨±‡“Î∞Ê R40£©
// Generated source version: 1.1.2

package com.amalto.core.webservice;


public class WSServiceAction {
    protected java.lang.String jndiName;
    protected com.amalto.core.webservice.WSServiceActionCode wsAction;
    protected java.lang.String methodName;
    protected java.lang.String[] methodParameters;
    
    public WSServiceAction() {
    }
    
    public WSServiceAction(java.lang.String jndiName, com.amalto.core.webservice.WSServiceActionCode wsAction, java.lang.String methodName, java.lang.String[] methodParameters) {
        this.jndiName = jndiName;
        this.wsAction = wsAction;
        this.methodName = methodName;
        this.methodParameters = methodParameters;
    }
    
    public java.lang.String getJndiName() {
        return jndiName;
    }
    
    public void setJndiName(java.lang.String jndiName) {
        this.jndiName = jndiName;
    }
    
    public com.amalto.core.webservice.WSServiceActionCode getWsAction() {
        return wsAction;
    }
    
    public void setWsAction(com.amalto.core.webservice.WSServiceActionCode wsAction) {
        this.wsAction = wsAction;
    }
    
    public java.lang.String getMethodName() {
        return methodName;
    }
    
    public void setMethodName(java.lang.String methodName) {
        this.methodName = methodName;
    }
    
    public java.lang.String[] getMethodParameters() {
        return methodParameters;
    }
    
    public void setMethodParameters(java.lang.String[] methodParameters) {
        this.methodParameters = methodParameters;
    }
}
