// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation £®1.1.2_01£¨±‡“Î∞Ê R40£©
// Generated source version: 1.1.2

package com.amalto.core.webservice;


public class WSSynchronizationItemPKArray {
    protected com.amalto.core.webservice.WSSynchronizationItemPK[] wsSynchronizationItemPK;
    
    public WSSynchronizationItemPKArray() {
    }
    
    public WSSynchronizationItemPKArray(com.amalto.core.webservice.WSSynchronizationItemPK[] wsSynchronizationItemPK) {
        this.wsSynchronizationItemPK = wsSynchronizationItemPK;
    }
    
    public com.amalto.core.webservice.WSSynchronizationItemPK[] getWsSynchronizationItemPK() {
        return wsSynchronizationItemPK;
    }
    
    public void setWsSynchronizationItemPK(com.amalto.core.webservice.WSSynchronizationItemPK[] wsSynchronizationItemPK) {
        this.wsSynchronizationItemPK = wsSynchronizationItemPK;
    }
}
