// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation £®1.1.2_01£¨±‡“Î∞Ê R40£©
// Generated source version: 1.1.2

package com.amalto.core.webservice;


public class WSUniverseXtentisObjectsRevisionIDs {
    protected java.lang.String xtentisObjectName;
    protected java.lang.String revisionID;
    
    public WSUniverseXtentisObjectsRevisionIDs() {
    }
    
    public WSUniverseXtentisObjectsRevisionIDs(java.lang.String xtentisObjectName, java.lang.String revisionID) {
        this.xtentisObjectName = xtentisObjectName;
        this.revisionID = revisionID;
    }
    
    public java.lang.String getXtentisObjectName() {
        return xtentisObjectName;
    }
    
    public void setXtentisObjectName(java.lang.String xtentisObjectName) {
        this.xtentisObjectName = xtentisObjectName;
    }
    
    public java.lang.String getRevisionID() {
        return revisionID;
    }
    
    public void setRevisionID(java.lang.String revisionID) {
        this.revisionID = revisionID;
    }
}
