// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation £®1.1.2_01£¨±‡“Î∞Ê R40£©
// Generated source version: 1.1.2

package com.amalto.core.webservice;


public class WSWhereOr {
    protected com.amalto.core.webservice.WSWhereItem[] whereItems;
    
    public WSWhereOr() {
    }
    
    public WSWhereOr(com.amalto.core.webservice.WSWhereItem[] whereItems) {
        this.whereItems = whereItems;
    }
    
    public com.amalto.core.webservice.WSWhereItem[] getWhereItems() {
        return whereItems;
    }
    
    public void setWhereItems(com.amalto.core.webservice.WSWhereItem[] whereItems) {
        this.whereItems = whereItems;
    }
}
