// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation £®1.1.2_01£¨±‡“Î∞Ê R40£©
// Generated source version: 1.1.2

package com.amalto.core.webservice;


public class WSWhereItem {
    protected com.amalto.core.webservice.WSWhereCondition whereCondition;
    protected com.amalto.core.webservice.WSWhereAnd whereAnd;
    protected com.amalto.core.webservice.WSWhereOr whereOr;
    
    public WSWhereItem() {
    }
    
    public WSWhereItem(com.amalto.core.webservice.WSWhereCondition whereCondition, com.amalto.core.webservice.WSWhereAnd whereAnd, com.amalto.core.webservice.WSWhereOr whereOr) {
        this.whereCondition = whereCondition;
        this.whereAnd = whereAnd;
        this.whereOr = whereOr;
    }
    
    public com.amalto.core.webservice.WSWhereCondition getWhereCondition() {
        return whereCondition;
    }
    
    public void setWhereCondition(com.amalto.core.webservice.WSWhereCondition whereCondition) {
        this.whereCondition = whereCondition;
    }
    
    public com.amalto.core.webservice.WSWhereAnd getWhereAnd() {
        return whereAnd;
    }
    
    public void setWhereAnd(com.amalto.core.webservice.WSWhereAnd whereAnd) {
        this.whereAnd = whereAnd;
    }
    
    public com.amalto.core.webservice.WSWhereOr getWhereOr() {
        return whereOr;
    }
    
    public void setWhereOr(com.amalto.core.webservice.WSWhereOr whereOr) {
        this.whereOr = whereOr;
    }
}
