 /*
 * Generated by XDoclet - Do not edit!
 * this class was prodiuced by xdoclet automagically...
 */
package com.amalto.core.ejb.remote;

import java.util.*;

/**
 * This class is remote adapter to DroppedItemCtrl. It provides convenient way to access
 * facade session bean. Inverit from this class to provide reasonable caching and event handling capabilities.
 *
 * Remote facade for DroppedItemCtrl.
 * @xdoclet-generated
 * @copyright The XDoclet Team
 * @author XDoclet
 * @version ${version}
 */

public class DroppedItemCtrlRemote extends Observable
{
    static DroppedItemCtrlRemote _instance = null;
    public static DroppedItemCtrlRemote getInstance() {
        if(_instance == null) {
	   _instance = new DroppedItemCtrlRemote();
	}
	return _instance;
    }

  /**
   * cached remote session interface
   */
  com.amalto.core.ejb.remote.DroppedItemCtrl _session = null;
  /**
   * return session bean remote interface
   */
   protected com.amalto.core.ejb.remote.DroppedItemCtrl getSession() {
      try {
   	if(_session == null) {
	   _session = com.amalto.core.ejb.local.DroppedItemCtrlUtil.getHome().create();
	}
	return _session;
      } catch(Exception ex) {
        // just catch it here and return null.
        // somebody can provide better solution
	ex.printStackTrace();
	return null;
      }
   }

   public com.amalto.core.ejb.ItemPOJOPK recoverDroppedItem ( com.amalto.core.ejb.DroppedItemPOJOPK droppedItemPOJOPK )
	  throws com.amalto.core.util.XtentisException, java.rmi.RemoteException
   {
        com.amalto.core.ejb.ItemPOJOPK retval;
       retval =  getSession().recoverDroppedItem( droppedItemPOJOPK );

      return retval;

   }

   public java.util.List findAllDroppedItemsPKs ( java.lang.String regex )
	  throws com.amalto.core.util.XtentisException, java.rmi.RemoteException
   {
        java.util.List retval;
       retval =  getSession().findAllDroppedItemsPKs( regex );

      return retval;

   }

   public com.amalto.core.ejb.DroppedItemPOJO loadDroppedItem ( com.amalto.core.ejb.DroppedItemPOJOPK droppedItemPOJOPK )
	  throws com.amalto.core.util.XtentisException, java.rmi.RemoteException
   {
        com.amalto.core.ejb.DroppedItemPOJO retval;
       retval =  getSession().loadDroppedItem( droppedItemPOJOPK );

      return retval;

   }

   public com.amalto.core.ejb.DroppedItemPOJOPK removeDroppedItem ( com.amalto.core.ejb.DroppedItemPOJOPK droppedItemPOJOPK )
	  throws com.amalto.core.util.XtentisException, java.rmi.RemoteException
   {
        com.amalto.core.ejb.DroppedItemPOJOPK retval;
       retval =  getSession().removeDroppedItem( droppedItemPOJOPK );

      return retval;

   }

  /**
   * override this method to provide feedback to interested objects
   * in case collections were changed.
   */
  public void invalidate() {

  	setChanged();
	notifyObservers();
  }
}
