/*
 * Generated by XDoclet - Do not edit!
 */
package org.talend.mdm.service.calljob.ejb.local;

/**
 * Local home interface for CallJobServiceBean.
 * @xdoclet-generated at 22-03-10
 * @copyright The XDoclet Team
 * @author XDoclet
 * @version ${version}
 */
public interface CallJobServiceBeanLocalHome
   extends javax.ejb.EJBLocalHome
{
   public static final String COMP_NAME="java:comp/env/ejb/CallJobServiceBeanLocal";
   public static final String JNDI_NAME="amalto/local/service/callJob";

   public org.talend.mdm.service.calljob.ejb.local.CallJobServiceBeanLocal create()
      throws javax.ejb.CreateException;

}
