/*
 * Generated by XDoclet - Do not edit!
 */
package com.amalto.service.autovalidation.ejb.local;

/**
 * Session layer for AutoValidationBean.
 * @xdoclet-generated at 29-04-10
 * @copyright The XDoclet Team
 * @author XDoclet
 * @version ${version}
 */
public class AutoValidationBeanSession
   extends com.amalto.service.autovalidation.ejb.AutoValidationBean
   implements javax.ejb.SessionBean
{
   public void ejbActivate() 
   {

   }

   public void ejbPassivate() 
   {
   }

   public void setSessionContext(javax.ejb.SessionContext ctx) 
   {
   }

   public void unsetSessionContext() 
   {
   }

   public void ejbRemove() 
   {
   }

   public void ejbCreate() throws javax.ejb.CreateException
   {
   }

}
