// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation £®1.1.2_01£¨±‡“Î∞Ê R40£©
// Generated source version: 1.1.2

package com.amalto.core.webservice;


public class WSConceptRevisionMapMapEntry {
    protected java.lang.String concept;
    protected java.lang.String revision;
    
    public WSConceptRevisionMapMapEntry() {
    }
    
    public WSConceptRevisionMapMapEntry(java.lang.String concept, java.lang.String revision) {
        this.concept = concept;
        this.revision = revision;
    }
    
    public java.lang.String getConcept() {
        return concept;
    }
    
    public void setConcept(java.lang.String concept) {
        this.concept = concept;
    }
    
    public java.lang.String getRevision() {
        return revision;
    }
    
    public void setRevision(java.lang.String revision) {
        this.revision = revision;
    }
}
