// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation £®1.1.2_01£¨±‡“Î∞Ê R40£©
// Generated source version: 1.1.2

package com.amalto.core.webservice;


public class WSPutStoredProcedure {
    protected com.amalto.core.webservice.WSStoredProcedure wsStoredProcedure;
    
    public WSPutStoredProcedure() {
    }
    
    public WSPutStoredProcedure(com.amalto.core.webservice.WSStoredProcedure wsStoredProcedure) {
        this.wsStoredProcedure = wsStoredProcedure;
    }
    
    public com.amalto.core.webservice.WSStoredProcedure getWsStoredProcedure() {
        return wsStoredProcedure;
    }
    
    public void setWsStoredProcedure(com.amalto.core.webservice.WSStoredProcedure wsStoredProcedure) {
        this.wsStoredProcedure = wsStoredProcedure;
    }
}
