// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation £®1.1.2_01£¨±‡“Î∞Ê R40£©
// Generated source version: 1.1.2

package com.amalto.core.webservice;


public class WSTransformerPluginV2SListItem {
    protected java.lang.String jndiName;
    protected java.lang.String description;
    
    public WSTransformerPluginV2SListItem() {
    }
    
    public WSTransformerPluginV2SListItem(java.lang.String jndiName, java.lang.String description) {
        this.jndiName = jndiName;
        this.description = description;
    }
    
    public java.lang.String getJndiName() {
        return jndiName;
    }
    
    public void setJndiName(java.lang.String jndiName) {
        this.jndiName = jndiName;
    }
    
    public java.lang.String getDescription() {
        return description;
    }
    
    public void setDescription(java.lang.String description) {
        this.description = description;
    }
}
