// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation £®1.1.2_01£¨±‡“Î∞Ê R40£©
// Generated source version: 1.1.2

package com.amalto.core.webservice;


public class WSVersioningItemHistory {
    protected com.amalto.core.webservice.WSItemPK wsItemPK;
    protected com.amalto.core.webservice.WSVersioningHistoryEntry[] wsHistoryEntries;
    
    public WSVersioningItemHistory() {
    }
    
    public WSVersioningItemHistory(com.amalto.core.webservice.WSItemPK wsItemPK, com.amalto.core.webservice.WSVersioningHistoryEntry[] wsHistoryEntries) {
        this.wsItemPK = wsItemPK;
        this.wsHistoryEntries = wsHistoryEntries;
    }
    
    public com.amalto.core.webservice.WSItemPK getWsItemPK() {
        return wsItemPK;
    }
    
    public void setWsItemPK(com.amalto.core.webservice.WSItemPK wsItemPK) {
        this.wsItemPK = wsItemPK;
    }
    
    public com.amalto.core.webservice.WSVersioningHistoryEntry[] getWsHistoryEntries() {
        return wsHistoryEntries;
    }
    
    public void setWsHistoryEntries(com.amalto.core.webservice.WSVersioningHistoryEntry[] wsHistoryEntries) {
        this.wsHistoryEntries = wsHistoryEntries;
    }
}
