// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation £®1.1.2_01£¨±‡“Î∞Ê R40£©
// Generated source version: 1.1.2

package com.amalto.core.webservice;


public class WSVersioningSystemConfiguration {
    protected java.lang.String name;
    protected java.lang.String description;
    protected java.lang.String url;
    protected java.lang.String username;
    protected java.lang.String password;
    
    public WSVersioningSystemConfiguration() {
    }
    
    public WSVersioningSystemConfiguration(java.lang.String name, java.lang.String description, java.lang.String url, java.lang.String username, java.lang.String password) {
        this.name = name;
        this.description = description;
        this.url = url;
        this.username = username;
        this.password = password;
    }
    
    public java.lang.String getName() {
        return name;
    }
    
    public void setName(java.lang.String name) {
        this.name = name;
    }
    
    public java.lang.String getDescription() {
        return description;
    }
    
    public void setDescription(java.lang.String description) {
        this.description = description;
    }
    
    public java.lang.String getUrl() {
        return url;
    }
    
    public void setUrl(java.lang.String url) {
        this.url = url;
    }
    
    public java.lang.String getUsername() {
        return username;
    }
    
    public void setUsername(java.lang.String username) {
        this.username = username;
    }
    
    public java.lang.String getPassword() {
        return password;
    }
    
    public void setPassword(java.lang.String password) {
        this.password = password;
    }
}
