// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation £®1.1.2_01£¨±‡“Î∞Ê R40£©
// Generated source version: 1.1.2

package com.amalto.core.webservice;


public class WSVersioningTagUniverse {
    protected java.lang.String versioningSystemName;
    protected java.lang.String tag;
    protected java.lang.String comment;
    protected com.amalto.core.webservice.WSLinkedHashMap typeInstances;
    
    public WSVersioningTagUniverse() {
    }
    
    public WSVersioningTagUniverse(java.lang.String versioningSystemName, java.lang.String tag, java.lang.String comment, com.amalto.core.webservice.WSLinkedHashMap typeInstances) {
        this.versioningSystemName = versioningSystemName;
        this.tag = tag;
        this.comment = comment;
        this.typeInstances = typeInstances;
    }
    
    public java.lang.String getVersioningSystemName() {
        return versioningSystemName;
    }
    
    public void setVersioningSystemName(java.lang.String versioningSystemName) {
        this.versioningSystemName = versioningSystemName;
    }
    
    public java.lang.String getTag() {
        return tag;
    }
    
    public void setTag(java.lang.String tag) {
        this.tag = tag;
    }
    
    public java.lang.String getComment() {
        return comment;
    }
    
    public void setComment(java.lang.String comment) {
        this.comment = comment;
    }
    
    public com.amalto.core.webservice.WSLinkedHashMap getTypeInstances() {
        return typeInstances;
    }
    
    public void setTypeInstances(com.amalto.core.webservice.WSLinkedHashMap typeInstances) {
        this.typeInstances = typeInstances;
    }
}
