// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation £®1.1.2_01£¨±‡“Î∞Ê R40£©
// Generated source version: 1.1.2

package com.amalto.core.webservice;


public class WSWorkflowDeleteProcessInstancesRequest {
    protected java.lang.String processName;
    
    public WSWorkflowDeleteProcessInstancesRequest() {
    }
    
    public WSWorkflowDeleteProcessInstancesRequest(java.lang.String processName) {
        this.processName = processName;
    }
    
    public java.lang.String getProcessName() {
        return processName;
    }
    
    public void setProcessName(java.lang.String processName) {
        this.processName = processName;
    }
}
