<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="mdmproperties" nsURI="http://www.talend.org/mdmproperties" nsPrefix="mdmproperties">
  <eClassifiers xsi:type="ecore:EClass" name="MDMItem" eSuperTypes="../../org.talend.model/model/properties.ecore#//Item"/>
  <eClassifiers xsi:type="ecore:EClass" name="MDMServerDefItem" eSuperTypes="#//MDMItem">
    <eStructuralFeatures xsi:type="ecore:EReference" name="serverDef" eType="ecore:EClass MDMMetadata.ecore#//MDMServerDef"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MDMServerObjectItem" eSuperTypes="#//MDMItem">
    <eOperations name="getMDMServerObject" eType="ecore:EClass MDMServerObject.ecore#//MDMServerObject"/>
    <eOperations name="setMDMServerObject">
      <eParameters name="serverObj" eType="ecore:EClass MDMServerObject.ecore#//MDMServerObject"/>
    </eOperations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="WsMenuItem" eSuperTypes="#//MDMServerObjectItem">
    <eStructuralFeatures xsi:type="ecore:EReference" name="wsMenu" eType="ecore:EClass MDMServerObject.ecore#//WsMenuE"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="WsRoleItem" eSuperTypes="#//MDMServerObjectItem">
    <eStructuralFeatures xsi:type="ecore:EReference" name="wsRole" eType="ecore:EClass MDMServerObject.ecore#//WsRoleE"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ContainerItem" eSuperTypes="#//MDMItem ../../org.talend.model/model/properties.ecore#//FolderItem">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="label" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="repObjType" eType="#//ERepositoryObjectType"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="data" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EJavaObject"
        transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="ERepositoryObjectType" instanceClassName="org.talend.core.model.repository.ERepositoryObjectType"/>
  <eClassifiers xsi:type="ecore:EClass" name="WsDataModelItem" eSuperTypes="#//MDMServerObjectItem">
    <eStructuralFeatures xsi:type="ecore:EReference" name="wsDataModel" eType="ecore:EClass MDMServerObject.ecore#//WsDataModelE"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="WsDataClusterItem" eSuperTypes="#//MDMServerObjectItem">
    <eStructuralFeatures xsi:type="ecore:EReference" name="wsDataCluster" eType="ecore:EClass MDMServerObject.ecore#//WsDataClusterE"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="WsStoredProcedureItem" eSuperTypes="#//MDMServerObjectItem">
    <eStructuralFeatures xsi:type="ecore:EReference" name="wsStoredProcedure" eType="ecore:EClass MDMServerObject.ecore#//WsStoredProcedureE"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="WsUniverseItem" eSuperTypes="#//MDMServerObjectItem">
    <eStructuralFeatures xsi:type="ecore:EReference" name="wsUniverse" eType="ecore:EClass MDMServerObject.ecore#//WsUniverseE"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="WsSynchronizationPlanItem" eSuperTypes="#//MDMServerObjectItem">
    <eStructuralFeatures xsi:type="ecore:EReference" name="wsSynchronizationPlan"
        eType="ecore:EClass MDMServerObject.ecore#//WsSynchronizationPlanE"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="WsViewItem" eSuperTypes="#//MDMServerObjectItem">
    <eStructuralFeatures xsi:type="ecore:EReference" name="wsView" eType="ecore:EClass MDMServerObject.ecore#//WsViewE"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="WsWorkflowDeployItem" eSuperTypes="#//MDMServerObjectItem">
    <eStructuralFeatures xsi:type="ecore:EReference" name="wsWorkflowDeploy" eType="ecore:EClass MDMServerObject.ecore#//WsWorkflowDeployE"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="WsTransformerV2Item" eSuperTypes="#//MDMServerObjectItem">
    <eStructuralFeatures xsi:type="ecore:EReference" name="wsTransformerV2" eType="ecore:EClass MDMServerObject.ecore#//WsTransformerV2E"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="WsRoutingRuleItem" eSuperTypes="#//MDMServerObjectItem">
    <eStructuralFeatures xsi:type="ecore:EReference" name="wsRoutingRule" eType="ecore:EClass MDMServerObject.ecore#//WsRoutingRuleE"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="WsJobModelItem" eSuperTypes="#//MDMServerObjectItem">
    <eStructuralFeatures xsi:type="ecore:EReference" name="wsJobModelItem" eType="ecore:EClass MDMServerObject.ecore#//WsJobModelE"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="WsEventManagerItem" eSuperTypes="#//MDMServerObjectItem">
    <eStructuralFeatures xsi:type="ecore:EReference" name="wsEventManager" eType="ecore:EClass MDMServerObject.ecore#//WsEventManagerE"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="WsServiceConfigurationItem" eSuperTypes="#//MDMServerObjectItem">
    <eStructuralFeatures xsi:type="ecore:EReference" name="wsServiceConfiguration"
        eType="ecore:EClass MDMServerObject.ecore#//WsServiceConfigurationE"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="WsWorkflowItem" eSuperTypes="#//MDMServerObjectItem">
    <eStructuralFeatures xsi:type="ecore:EReference" name="wsWorkflow" eType="ecore:EClass MDMServerObject.ecore#//WsWorkflowE"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="WsResourceItem" eSuperTypes="#//MDMServerObjectItem">
    <eStructuralFeatures xsi:type="ecore:EReference" name="resource" eType="ecore:EClass MDMServerObject.ecore#//WsResourceE"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="WsCustomFormItem" eSuperTypes="#//MDMServerObjectItem">
    <eStructuralFeatures xsi:type="ecore:EReference" name="customForm" eType="ecore:EClass MDMServerObject.ecore#//WsCustomFormE"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="WorkspaceRootItem" eSuperTypes="#//MDMItem ../../org.talend.model/model/properties.ecore#//FolderItem">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="label" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="WsMatchRuleItem" eSuperTypes="#//MDMServerObjectItem">
    <eStructuralFeatures xsi:type="ecore:EReference" name="mdmMatchRule" eType="ecore:EClass MDMServerObject.ecore#//WsMatchRuleE"/>
  </eClassifiers>
</ecore:EPackage>
