<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="mdmproperties"
    nsURI="http://www.talend.org/mdmproperties" nsPrefix="mdmproperties">
  <eClassifiers xsi:type="ecore:EClass" name="MDMItem" eSuperTypes="../../org.talend.model/model/properties.ecore#//Item"/>
  <eClassifiers xsi:type="ecore:EClass" name="MDMServerDefItem" eSuperTypes="#//MDMItem">
    <eStructuralFeatures xsi:type="ecore:EReference" name="serverDef" eType="ecore:EClass MDMMetadata.ecore#//MDMServerDef"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MDMServerObjectItem" eSuperTypes="#//MDMItem">
    <eOperations name="getMDMServerObject" eType="ecore:EClass MDMServerObject.ecore#//MDMServerObject"/>
    <eOperations name="setMDMServerObject">
      <eParameters name="serverObj" eType="ecore:EClass MDMServerObject.ecore#//MDMServerObject"/>
    </eOperations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="WSMenuItem" eSuperTypes="#//MDMServerObjectItem">
    <eStructuralFeatures xsi:type="ecore:EReference" name="wsMenu" eType="ecore:EClass MDMServerObject.ecore#//WSMenuE"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="WSRoleItem" eSuperTypes="#//MDMServerObjectItem">
    <eStructuralFeatures xsi:type="ecore:EReference" name="wsRole" eType="ecore:EClass MDMServerObject.ecore#//WSRoleE"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ContainerItem" eSuperTypes="#//MDMItem ../../org.talend.model/model/properties.ecore#//FolderItem">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="label" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="repObjType" eType="#//ERepositoryObjectType"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="data" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EJavaObject"
        transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="ERepositoryObjectType" instanceClassName="org.talend.core.model.repository.ERepositoryObjectType"/>
  <eClassifiers xsi:type="ecore:EClass" name="WSDataModelItem" eSuperTypes="#//MDMServerObjectItem">
    <eStructuralFeatures xsi:type="ecore:EReference" name="wsDataModel" eType="ecore:EClass MDMServerObject.ecore#//WSDataModelE"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="WSDataClusterItem" eSuperTypes="#//MDMServerObjectItem">
    <eStructuralFeatures xsi:type="ecore:EReference" name="wsDataCluster" eType="ecore:EClass MDMServerObject.ecore#//WSDataClusterE"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="WSStoredProcedureItem" eSuperTypes="#//MDMServerObjectItem">
    <eStructuralFeatures xsi:type="ecore:EReference" name="wsStoredProcedure" eType="ecore:EClass MDMServerObject.ecore#//WSStoredProcedureE"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="WSViewItem" eSuperTypes="#//MDMServerObjectItem">
    <eStructuralFeatures xsi:type="ecore:EReference" name="wsView" eType="ecore:EClass MDMServerObject.ecore#//WSViewE"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="WSWorkflowDeployItem" eSuperTypes="#//MDMServerObjectItem">
    <eStructuralFeatures xsi:type="ecore:EReference" name="wsWorkflowDeploy" eType="ecore:EClass MDMServerObject.ecore#//WSWorkflowDeployE"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="WSTransformerV2Item" eSuperTypes="#//MDMServerObjectItem">
    <eStructuralFeatures xsi:type="ecore:EReference" name="wsTransformerV2" eType="ecore:EClass MDMServerObject.ecore#//WSTransformerV2E"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="WSRoutingRuleItem" eSuperTypes="#//MDMServerObjectItem">
    <eStructuralFeatures xsi:type="ecore:EReference" name="wsRoutingRule" eType="ecore:EClass MDMServerObject.ecore#//WSRoutingRuleE"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="WSJobModelItem" eSuperTypes="#//MDMServerObjectItem">
    <eStructuralFeatures xsi:type="ecore:EReference" name="wsJobModelItem" eType="ecore:EClass MDMServerObject.ecore#//WSJobModelE"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="WSEventManagerItem" eSuperTypes="#//MDMServerObjectItem">
    <eStructuralFeatures xsi:type="ecore:EReference" name="wsEventManager" eType="ecore:EClass MDMServerObject.ecore#//WSEventManagerE"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="WSServiceConfigurationItem" eSuperTypes="#//MDMServerObjectItem">
    <eStructuralFeatures xsi:type="ecore:EReference" name="wsServiceConfiguration"
        eType="ecore:EClass MDMServerObject.ecore#//WSServiceConfigurationE"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="WSWorkflowItem" eSuperTypes="#//MDMServerObjectItem">
    <eStructuralFeatures xsi:type="ecore:EReference" name="wsWorkflow" eType="ecore:EClass MDMServerObject.ecore#//WSWorkflowE"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="WSResourceItem" eSuperTypes="#//MDMServerObjectItem">
    <eStructuralFeatures xsi:type="ecore:EReference" name="resource" eType="ecore:EClass MDMServerObject.ecore#//WSResourceE"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="WSCustomFormItem" eSuperTypes="#//MDMServerObjectItem">
    <eStructuralFeatures xsi:type="ecore:EReference" name="customForm" eType="ecore:EClass MDMServerObject.ecore#//WSCustomFormE"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="WorkspaceRootItem" eSuperTypes="#//MDMItem ../../org.talend.model/model/properties.ecore#//FolderItem">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="label" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="WSMatchRuleItem" eSuperTypes="#//MDMServerObjectItem">
    <eStructuralFeatures xsi:type="ecore:EReference" name="mdmMatchRule" eType="ecore:EClass MDMServerObject.ecore#//WSMatchRuleE"/>
  </eClassifiers>
</ecore:EPackage>
