<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="mdmserverobject" nsURI="http://www.talend.org/mdmserverobject"
    nsPrefix="mdmserverobject">
  <eClassifiers xsi:type="ecore:EClass" name="MDMServerObject">
    <eOperations name="getUniqueName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="description" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="system" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="lastServerDef" eType="ecore:EClass MDMMetadata.ecore#//MDMServerDef"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="timestamp" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELong"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="digestValue" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="currentDigestValue" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EString"
        transient="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="lastServerName" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="WSMenuE" eSuperTypes="#//MDMServerObject">
    <eStructuralFeatures xsi:type="ecore:EReference" name="menuEntries" upperBound="-1"
        eType="#//WSMenuEntryE" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="WSMenuEntryE">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="application" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="context" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="icon" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="descriptions" upperBound="-1"
        eType="#//WSMenuMenuEntriesDescriptionsE" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="subMenus" upperBound="-1"
        eType="#//WSMenuEntryE" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="WSMenuMenuEntriesDescriptionsE">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="language" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="label" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="WSRoleE" eSuperTypes="#//MDMServerObject">
    <eStructuralFeatures xsi:type="ecore:EReference" name="specification" upperBound="-1"
        eType="#//WSRoleSpecificationE" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="WSRoleSpecificationE">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="admin" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="objectType" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="instance" upperBound="-1"
        eType="#//WSRoleSpecificationInstanceE" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="WSRoleSpecificationInstanceE">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="instanceName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="writable" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="parameter" upperBound="-1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="WSViewE" eSuperTypes="#//MDMServerObject">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="searchableBusinessElements"
        upperBound="-1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="viewableBusinessElements"
        upperBound="-1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="transformerActive" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="whereConditions" upperBound="-1"
        eType="#//WSWhereConditionE" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="isTransformerActive" eType="#//WSBooleanE"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="transformerPK" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="sortField" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="isAsc" eType="#//WSBooleanE"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="customForm" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="WSWhereConditionE">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="leftPath" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="rightValueOrPath" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="stringPredicate" eType="#//WSStringPredicateE"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="operator" eType="#//WSWhereOperatorE"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="spellCheck" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="WSWhereOperatorE">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="WSStringPredicateE">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="WSDataModelE" eSuperTypes="#//MDMServerObject">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="xsdSchema" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="WSDataClusterE" eSuperTypes="#//MDMServerObject">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="vocabulary" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="WSStoredProcedureE" eSuperTypes="#//MDMServerObject">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="procedure" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="refreshCache" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="WSBooleanE">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="_true" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="WSWorkflowDeployE" eSuperTypes="#//MDMServerObject">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="filename" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="WSTransformerV2E" eSuperTypes="#//MDMServerObject">
    <eStructuralFeatures xsi:type="ecore:EReference" name="processSteps" upperBound="-1"
        eType="#//WSTransformerProcessStepE" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="WSTransformerProcessStepE">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="pluginJNDI" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="description" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="parameters" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="disabled" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="inputMappings" upperBound="-1"
        eType="#//WSTransformerVariablesMappingE" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="outputMappings" upperBound="-1"
        eType="#//WSTransformerVariablesMappingE" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="WSTransformerVariablesMappingE">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="pipelineVariable" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="pluginVariable" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="hardCoding" eType="#//WSTypedContentE"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="WSTypedContentE">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="url" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="contentType" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="wsBytes" eType="#//WSByteArrayE"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="WSByteArrayE">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="bytes" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EByteArray"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="WSRoutingRuleE" eSuperTypes="#//MDMServerObject">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="synchronous" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="concept" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="serviceJNDI" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="parameters" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="condition" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="deactive" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="executeOrder" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="wsRoutingRuleExpressions"
        upperBound="-1" eType="#//WSRoutingRuleExpressionE" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="WSRoutingRuleExpressionE">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="xpath" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="wsOperator" eType="#//WSRoutingRuleOperatorE"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="WSRoutingRuleOperatorE">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="WSJobModelE" eSuperTypes="#//MDMServerObject"/>
  <eClassifiers xsi:type="ecore:EClass" name="WSEventManagerE" eSuperTypes="#//MDMServerObject"/>
  <eClassifiers xsi:type="ecore:EClass" name="WSServiceConfigurationE" eSuperTypes="#//MDMServerObject">
    <eStructuralFeatures xsi:type="ecore:EReference" name="servicePutConfigurations"
        upperBound="-1" eType="#//WSServicePutConfigurationE" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="WSServicePutConfigurationE">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="jndiName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="configuration" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="WSWorkflowE" eSuperTypes="#//MDMServerObject">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="fileContent" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EByteArray"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="WSResourceE" eSuperTypes="#//MDMServerObject">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="fileExtension" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="fileContent" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EByteArray"
        transient="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="imageCatalog" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral="Default_Catalog"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="WSCustomFormE" eSuperTypes="#//MDMServerObject">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="filename" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="datamodel" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="entity" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="xml" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="role" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="WSMatchRuleE" eSuperTypes="#//MDMServerObject">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="configurationXmlContent"
        eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="PK" eType="#//WSMatchRulePKE"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="WSMatchRulePKE">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="pk" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EString"/>
  </eClassifiers>
  <eSubpackages name="matchrule" nsURI="http://www.talend.org/mdm/server/matchrule"
      nsPrefix="matchrule">
    <eClassifiers xsi:type="ecore:EClass" name="MatchRuleMapInfo">
      <eStructuralFeatures xsi:type="ecore:EReference" name="entityMapInfos" upperBound="-1"
          eType="#//matchrule/EntityMapInfo" containment="true" eOpposite="#//matchrule/EntityMapInfo/parent"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="modelName" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="EntityMapInfo">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="entityName" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="survivorshipKeyMap" upperBound="-1"
          eType="#//matchrule/KeyXPathMap" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="blockingKeyDefinition"
          eType="#//matchrule/BlockingKeyDefinition" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="matchRuleDefName" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="parent" eType="#//matchrule/MatchRuleMapInfo"
          eOpposite="#//matchrule/MatchRuleMapInfo/entityMapInfos"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="matchRuleMapInfoPages"
          upperBound="-1" eType="#//matchrule/MatchRuleMapInfoPage" containment="true"
          eOpposite="#//matchrule/MatchRuleMapInfoPage/parent"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="MatchRuleMapInfoPage">
      <eStructuralFeatures xsi:type="ecore:EReference" name="matchKeyMap" upperBound="-1"
          eType="#//matchrule/KeyXPathMap" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="parent" eType="#//matchrule/EntityMapInfo"
          eOpposite="#//matchrule/EntityMapInfo/matchRuleMapInfoPages"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="KeyXPathMap" instanceClassName="java.util.Map$Entry">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="key" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="BlockingKeyDefinition">
      <eStructuralFeatures xsi:type="ecore:EReference" name="blockingKeys" upperBound="-1"
          eType="#//matchrule/BlockingKey" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="useBuiltInColumn" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EBoolean"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="BlockingKey">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="keyName" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="MatchRuleMapInfoContainer">
      <eStructuralFeatures xsi:type="ecore:EReference" name="mapInfos" eType="#//matchrule/MatchRuleMapInfo"
          containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="matchRuleDefinitions"
          upperBound="-1" eType="ecore:EClass ../../org.talend.dataquality/model/dataquality.ecore#//rules/MatchRuleDefinition"
          containment="true"/>
    </eClassifiers>
  </eSubpackages>
</ecore:EPackage>
