// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation £®1.1.2_01£¨±‡“Î∞Ê R40£©
// Generated source version: 1.1.2

package com.amalto.core.webservice;


public class WSItemPKsByCriteriaResponse {
    protected com.amalto.core.webservice.WSItemPKsByCriteriaResponseResults[] results;
    
    public WSItemPKsByCriteriaResponse() {
    }
    
    public WSItemPKsByCriteriaResponse(com.amalto.core.webservice.WSItemPKsByCriteriaResponseResults[] results) {
        this.results = results;
    }
    
    public com.amalto.core.webservice.WSItemPKsByCriteriaResponseResults[] getResults() {
        return results;
    }
    
    public void setResults(com.amalto.core.webservice.WSItemPKsByCriteriaResponseResults[] results) {
        this.results = results;
    }
}
