// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation £®1.1.2_01£¨±‡“Î∞Ê R40£©
// Generated source version: 1.1.2

package com.amalto.webapp.util.webservices;


public class WSBoolean {
    protected boolean _true;
    
    public WSBoolean() {
    }
    
    public WSBoolean(boolean _true) {
        this._true = _true;
    }
    
    public boolean is_true() {
        return _true;
    }
    
    public void set_true(boolean _true) {
        this._true = _true;
    }
}
