// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation £®1.1.2_01£¨±‡“Î∞Ê R40£©
// Generated source version: 1.1.2

package com.amalto.webapp.util.webservices;


public class WSDropItem {
    protected com.amalto.webapp.util.webservices.WSItemPK wsItemPK;
    protected java.lang.String partPath;
    
    public WSDropItem() {
    }
    
    public WSDropItem(com.amalto.webapp.util.webservices.WSItemPK wsItemPK, java.lang.String partPath) {
        this.wsItemPK = wsItemPK;
        this.partPath = partPath;
    }
    
    public com.amalto.webapp.util.webservices.WSItemPK getWsItemPK() {
        return wsItemPK;
    }
    
    public void setWsItemPK(com.amalto.webapp.util.webservices.WSItemPK wsItemPK) {
        this.wsItemPK = wsItemPK;
    }
    
    public java.lang.String getPartPath() {
        return partPath;
    }
    
    public void setPartPath(java.lang.String partPath) {
        this.partPath = partPath;
    }
}
