// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation £®1.1.2_01£¨±‡“Î∞Ê R40£©
// Generated source version: 1.1.2

package com.amalto.webapp.util.webservices;


public class WSExtractUsingTransformer {
    protected com.amalto.webapp.util.webservices.WSItemPK wsItemPK;
    protected com.amalto.webapp.util.webservices.WSTransformerPK wsTransformerPK;
    
    public WSExtractUsingTransformer() {
    }
    
    public WSExtractUsingTransformer(com.amalto.webapp.util.webservices.WSItemPK wsItemPK, com.amalto.webapp.util.webservices.WSTransformerPK wsTransformerPK) {
        this.wsItemPK = wsItemPK;
        this.wsTransformerPK = wsTransformerPK;
    }
    
    public com.amalto.webapp.util.webservices.WSItemPK getWsItemPK() {
        return wsItemPK;
    }
    
    public void setWsItemPK(com.amalto.webapp.util.webservices.WSItemPK wsItemPK) {
        this.wsItemPK = wsItemPK;
    }
    
    public com.amalto.webapp.util.webservices.WSTransformerPK getWsTransformerPK() {
        return wsTransformerPK;
    }
    
    public void setWsTransformerPK(com.amalto.webapp.util.webservices.WSTransformerPK wsTransformerPK) {
        this.wsTransformerPK = wsTransformerPK;
    }
}
