// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation £®1.1.2_01£¨±‡“Î∞Ê R40£©
// Generated source version: 1.1.2

package com.amalto.webapp.util.webservices;


public class WSMenuMenuEntriesDescriptions {
    protected java.lang.String language;
    protected java.lang.String label;
    
    public WSMenuMenuEntriesDescriptions() {
    }
    
    public WSMenuMenuEntriesDescriptions(java.lang.String language, java.lang.String label) {
        this.language = language;
        this.label = label;
    }
    
    public java.lang.String getLanguage() {
        return language;
    }
    
    public void setLanguage(java.lang.String language) {
        this.language = language;
    }
    
    public java.lang.String getLabel() {
        return label;
    }
    
    public void setLabel(java.lang.String label) {
        this.label = label;
    }
}
