// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation £®1.1.2_01£¨±‡“Î∞Ê R40£©
// Generated source version: 1.1.2

package com.amalto.webapp.util.webservices;


public class WSRoutingRuleExpression {
    protected java.lang.String name;
    protected java.lang.String xpath;
    protected com.amalto.webapp.util.webservices.WSRoutingRuleOperator wsOperator;
    protected java.lang.String value;
    
    public WSRoutingRuleExpression() {
    }
    
    public WSRoutingRuleExpression(java.lang.String name, java.lang.String xpath, com.amalto.webapp.util.webservices.WSRoutingRuleOperator wsOperator, java.lang.String value) {
        this.name = name;
        this.xpath = xpath;
        this.wsOperator = wsOperator;
        this.value = value;
    }
    
    public java.lang.String getName() {
        return name;
    }
    
    public void setName(java.lang.String name) {
        this.name = name;
    }
    
    public java.lang.String getXpath() {
        return xpath;
    }
    
    public void setXpath(java.lang.String xpath) {
        this.xpath = xpath;
    }
    
    public com.amalto.webapp.util.webservices.WSRoutingRuleOperator getWsOperator() {
        return wsOperator;
    }
    
    public void setWsOperator(com.amalto.webapp.util.webservices.WSRoutingRuleOperator wsOperator) {
        this.wsOperator = wsOperator;
    }
    
    public java.lang.String getValue() {
        return value;
    }
    
    public void setValue(java.lang.String value) {
        this.value = value;
    }
}
