// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation £®1.1.2_01£¨±‡“Î∞Ê R40£©
// Generated source version: 1.1.2

package com.amalto.webapp.util.webservices;


public class WSSynchronizationGetItemXML {
    protected java.lang.String revisionID;
    protected com.amalto.webapp.util.webservices.WSItemPK wsItemPOJOPK;
    
    public WSSynchronizationGetItemXML() {
    }
    
    public WSSynchronizationGetItemXML(java.lang.String revisionID, com.amalto.webapp.util.webservices.WSItemPK wsItemPOJOPK) {
        this.revisionID = revisionID;
        this.wsItemPOJOPK = wsItemPOJOPK;
    }
    
    public java.lang.String getRevisionID() {
        return revisionID;
    }
    
    public void setRevisionID(java.lang.String revisionID) {
        this.revisionID = revisionID;
    }
    
    public com.amalto.webapp.util.webservices.WSItemPK getWsItemPOJOPK() {
        return wsItemPOJOPK;
    }
    
    public void setWsItemPOJOPK(com.amalto.webapp.util.webservices.WSItemPK wsItemPOJOPK) {
        this.wsItemPOJOPK = wsItemPOJOPK;
    }
}
