// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation £®1.1.2_01£¨±‡“Î∞Ê R40£©
// Generated source version: 1.1.2

package com.amalto.webapp.util.webservices;


public class WSTransformerPluginV2PutConfiguration {
    protected java.lang.String jndiName;
    protected java.lang.String configuration;
    
    public WSTransformerPluginV2PutConfiguration() {
    }
    
    public WSTransformerPluginV2PutConfiguration(java.lang.String jndiName, java.lang.String configuration) {
        this.jndiName = jndiName;
        this.configuration = configuration;
    }
    
    public java.lang.String getJndiName() {
        return jndiName;
    }
    
    public void setJndiName(java.lang.String jndiName) {
        this.jndiName = jndiName;
    }
    
    public java.lang.String getConfiguration() {
        return configuration;
    }
    
    public void setConfiguration(java.lang.String configuration) {
        this.configuration = configuration;
    }
}
