// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation £®1.1.2_01£¨±‡“Î∞Ê R40£©
// Generated source version: 1.1.2

package com.amalto.webapp.util.webservices;

import com.sun.xml.rpc.encoding.*;
import com.sun.xml.rpc.encoding.xsd.XSDConstants;
import com.sun.xml.rpc.encoding.literal.*;
import com.sun.xml.rpc.encoding.literal.DetailFragmentDeserializer;
import com.sun.xml.rpc.encoding.simpletype.*;
import com.sun.xml.rpc.encoding.soap.SOAPConstants;
import com.sun.xml.rpc.encoding.soap.SOAP12Constants;
import com.sun.xml.rpc.streaming.*;
import com.sun.xml.rpc.wsdl.document.schema.SchemaConstants;
import javax.xml.namespace.QName;
import java.util.List;
import java.util.ArrayList;

public class WSTransformerVariablesMapping_LiteralSerializer extends LiteralObjectSerializerBase implements Initializable  {
    private static final QName ns1_pipelineVariable_QNAME = new QName("", "pipelineVariable");
    private static final QName ns3_string_TYPE_QNAME = SchemaConstants.QNAME_TYPE_STRING;
    private CombinedSerializer ns3_myns3_string__java_lang_String_String_Serializer;
    private static final QName ns1_pluginVariable_QNAME = new QName("", "pluginVariable");
    private static final QName ns1_hardCoding_QNAME = new QName("", "hardCoding");
    private static final QName ns2_WSTypedContent_TYPE_QNAME = new QName("urn-com-amalto-xtentis-webservice", "WSTypedContent");
    private CombinedSerializer ns2_myWSTypedContent_LiteralSerializer;
    
    public WSTransformerVariablesMapping_LiteralSerializer(QName type, String encodingStyle) {
        this(type, encodingStyle, false);
    }
    
    public WSTransformerVariablesMapping_LiteralSerializer(QName type, String encodingStyle, boolean encodeType) {
        super(type, true, encodingStyle, encodeType);
    }
    
    public void initialize(InternalTypeMappingRegistry registry) throws Exception {
        ns3_myns3_string__java_lang_String_String_Serializer = (CombinedSerializer)registry.getSerializer("", java.lang.String.class, ns3_string_TYPE_QNAME);
        ns2_myWSTypedContent_LiteralSerializer = (CombinedSerializer)registry.getSerializer("", com.amalto.webapp.util.webservices.WSTypedContent.class, ns2_WSTypedContent_TYPE_QNAME);
    }
    
    public Object doDeserialize(XMLReader reader,
        SOAPDeserializationContext context) throws Exception {
        com.amalto.webapp.util.webservices.WSTransformerVariablesMapping instance = new com.amalto.webapp.util.webservices.WSTransformerVariablesMapping();
        Object member=null;
        QName elementName;
        List values;
        Object value;
        
        reader.nextElementContent();
        elementName = reader.getName();
        if (reader.getState() == XMLReader.START) {
            if (elementName.equals(ns1_pipelineVariable_QNAME)) {
                member = ns3_myns3_string__java_lang_String_String_Serializer.deserialize(ns1_pipelineVariable_QNAME, reader, context);
                instance.setPipelineVariable((java.lang.String)member);
                reader.nextElementContent();
            } else {
                throw new DeserializationException("literal.unexpectedElementName", new Object[] { ns1_pipelineVariable_QNAME, reader.getName() });
            }
        }
        else {
            throw new DeserializationException("literal.expectedElementName", reader.getName().toString());
        }
        elementName = reader.getName();
        if (reader.getState() == XMLReader.START) {
            if (elementName.equals(ns1_pluginVariable_QNAME)) {
                member = ns3_myns3_string__java_lang_String_String_Serializer.deserialize(ns1_pluginVariable_QNAME, reader, context);
                if (member == null) {
                    throw new DeserializationException("literal.unexpectedNull");
                }
                instance.setPluginVariable((java.lang.String)member);
                reader.nextElementContent();
            } else {
                throw new DeserializationException("literal.unexpectedElementName", new Object[] { ns1_pluginVariable_QNAME, reader.getName() });
            }
        }
        else {
            throw new DeserializationException("literal.expectedElementName", reader.getName().toString());
        }
        elementName = reader.getName();
        if (reader.getState() == XMLReader.START) {
            if (elementName.equals(ns1_hardCoding_QNAME)) {
                member = ns2_myWSTypedContent_LiteralSerializer.deserialize(ns1_hardCoding_QNAME, reader, context);
                instance.setHardCoding((com.amalto.webapp.util.webservices.WSTypedContent)member);
                reader.nextElementContent();
            }
        }
        
        XMLReaderUtil.verifyReaderState(reader, XMLReader.END);
        return (Object)instance;
    }
    
    public void doSerializeAttributes(Object obj, XMLWriter writer, SOAPSerializationContext context) throws Exception {
        com.amalto.webapp.util.webservices.WSTransformerVariablesMapping instance = (com.amalto.webapp.util.webservices.WSTransformerVariablesMapping)obj;
        
    }
    public void doSerialize(Object obj, XMLWriter writer, SOAPSerializationContext context) throws Exception {
        com.amalto.webapp.util.webservices.WSTransformerVariablesMapping instance = (com.amalto.webapp.util.webservices.WSTransformerVariablesMapping)obj;
        
        ns3_myns3_string__java_lang_String_String_Serializer.serialize(instance.getPipelineVariable(), ns1_pipelineVariable_QNAME, null, writer, context);
        if (instance.getPluginVariable() == null) {
            throw new SerializationException("literal.unexpectedNull");
        }
        ns3_myns3_string__java_lang_String_String_Serializer.serialize(instance.getPluginVariable(), ns1_pluginVariable_QNAME, null, writer, context);
        ns2_myWSTypedContent_LiteralSerializer.serialize(instance.getHardCoding(), ns1_hardCoding_QNAME, null, writer, context);
    }
}
