// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation £®1.1.2_01£¨±‡“Î∞Ê R40£©
// Generated source version: 1.1.2

package com.amalto.webapp.util.webservices;


public class WSTransformerContextPipelinePipelineItem {
    protected java.lang.String variable;
    protected com.amalto.webapp.util.webservices.WSTypedContent wsTypedContent;
    
    public WSTransformerContextPipelinePipelineItem() {
    }
    
    public WSTransformerContextPipelinePipelineItem(java.lang.String variable, com.amalto.webapp.util.webservices.WSTypedContent wsTypedContent) {
        this.variable = variable;
        this.wsTypedContent = wsTypedContent;
    }
    
    public java.lang.String getVariable() {
        return variable;
    }
    
    public void setVariable(java.lang.String variable) {
        this.variable = variable;
    }
    
    public com.amalto.webapp.util.webservices.WSTypedContent getWsTypedContent() {
        return wsTypedContent;
    }
    
    public void setWsTypedContent(com.amalto.webapp.util.webservices.WSTypedContent wsTypedContent) {
        this.wsTypedContent = wsTypedContent;
    }
}
