// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation £®1.1.2_01£¨±‡“Î∞Ê R40£©
// Generated source version: 1.1.2

package com.amalto.webapp.util.webservices;


public class WSUpdateReportItemArray {
    protected com.amalto.webapp.util.webservices.WSUpdateReportItemPOJO[] wsUpdateReportItemPOJO;
    
    public WSUpdateReportItemArray() {
    }
    
    public WSUpdateReportItemArray(com.amalto.webapp.util.webservices.WSUpdateReportItemPOJO[] wsUpdateReportItemPOJO) {
        this.wsUpdateReportItemPOJO = wsUpdateReportItemPOJO;
    }
    
    public com.amalto.webapp.util.webservices.WSUpdateReportItemPOJO[] getWsUpdateReportItemPOJO() {
        return wsUpdateReportItemPOJO;
    }
    
    public void setWsUpdateReportItemPOJO(com.amalto.webapp.util.webservices.WSUpdateReportItemPOJO[] wsUpdateReportItemPOJO) {
        this.wsUpdateReportItemPOJO = wsUpdateReportItemPOJO;
    }
}
