// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation £®1.1.2_01£¨±‡“Î∞Ê R40£©
// Generated source version: 1.1.2

package com.amalto.webapp.util.webservices;


public class WSVersioningRestoreObjects {
    protected java.lang.String versioningSystemName;
    protected java.lang.String tag;
    protected java.lang.String type;
    protected java.lang.String[] names;
    
    public WSVersioningRestoreObjects() {
    }
    
    public WSVersioningRestoreObjects(java.lang.String versioningSystemName, java.lang.String tag, java.lang.String type, java.lang.String[] names) {
        this.versioningSystemName = versioningSystemName;
        this.tag = tag;
        this.type = type;
        this.names = names;
    }
    
    public java.lang.String getVersioningSystemName() {
        return versioningSystemName;
    }
    
    public void setVersioningSystemName(java.lang.String versioningSystemName) {
        this.versioningSystemName = versioningSystemName;
    }
    
    public java.lang.String getTag() {
        return tag;
    }
    
    public void setTag(java.lang.String tag) {
        this.tag = tag;
    }
    
    public java.lang.String getType() {
        return type;
    }
    
    public void setType(java.lang.String type) {
        this.type = type;
    }
    
    public java.lang.String[] getNames() {
        return names;
    }
    
    public void setNames(java.lang.String[] names) {
        this.names = names;
    }
}
