/*
 * Generated by XDoclet - Do not edit!
 */
package com.amalto.core.objects.versioning.ejb.local;

/**
 * Local home interface for VersioningServiceCtrl.
 * @xdoclet-generated at 13-08-09
 * @copyright The XDoclet Team
 * @author XDoclet
 * @version ${version}
 */
public interface VersioningServiceCtrlLocalHome
   extends com.amalto.core.ejb.local.ServiceCtrlLocalHome
{

}
