// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation £®1.1.2_01£¨±‡“Î∞Ê R40£©
// Generated source version: 1.1.2

package com.amalto.webapp.util.webservices;


public class WSCheckServiceConfigRequest {
    protected java.lang.String jndiName;
    protected java.lang.String conf;
    
    public WSCheckServiceConfigRequest() {
    }
    
    public WSCheckServiceConfigRequest(java.lang.String jndiName, java.lang.String conf) {
        this.jndiName = jndiName;
        this.conf = conf;
    }
    
    public java.lang.String getJndiName() {
        return jndiName;
    }
    
    public void setJndiName(java.lang.String jndiName) {
        this.jndiName = jndiName;
    }
    
    public java.lang.String getConf() {
        return conf;
    }
    
    public void setConf(java.lang.String conf) {
        this.conf = conf;
    }
}
