// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation £®1.1.2_01£¨±‡“Î∞Ê R40£©
// Generated source version: 1.1.2

package com.amalto.webapp.util.webservices;


public class WSCheckSchema {
    protected java.lang.String schema;
    
    public WSCheckSchema() {
    }
    
    public WSCheckSchema(java.lang.String schema) {
        this.schema = schema;
    }
    
    public java.lang.String getSchema() {
        return schema;
    }
    
    public void setSchema(java.lang.String schema) {
        this.schema = schema;
    }
}
