// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation £®1.1.2_01£¨±‡“Î∞Ê R40£©
// Generated source version: 1.1.2

package com.amalto.webapp.util.webservices;


public class WSConceptRevisionMap {
    protected com.amalto.webapp.util.webservices.WSConceptRevisionMapMapEntry[] mapEntry;
    
    public WSConceptRevisionMap() {
    }
    
    public WSConceptRevisionMap(com.amalto.webapp.util.webservices.WSConceptRevisionMapMapEntry[] mapEntry) {
        this.mapEntry = mapEntry;
    }
    
    public com.amalto.webapp.util.webservices.WSConceptRevisionMapMapEntry[] getMapEntry() {
        return mapEntry;
    }
    
    public void setMapEntry(com.amalto.webapp.util.webservices.WSConceptRevisionMapMapEntry[] mapEntry) {
        this.mapEntry = mapEntry;
    }
}
