// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation £®1.1.2_01£¨±‡“Î∞Ê R40£©
// Generated source version: 1.1.2

package com.amalto.webapp.util.webservices;


public class WSConnectorInteraction {
    protected java.lang.String JNDIName;
    protected com.amalto.webapp.util.webservices.WSConnectorFunction function;
    protected com.amalto.webapp.util.webservices.WSBase64KeyValue[] parameters;
    
    public WSConnectorInteraction() {
    }
    
    public WSConnectorInteraction(java.lang.String JNDIName, com.amalto.webapp.util.webservices.WSConnectorFunction function, com.amalto.webapp.util.webservices.WSBase64KeyValue[] parameters) {
        this.JNDIName = JNDIName;
        this.function = function;
        this.parameters = parameters;
    }
    
    public java.lang.String getJNDIName() {
        return JNDIName;
    }
    
    public void setJNDIName(java.lang.String JNDIName) {
        this.JNDIName = JNDIName;
    }
    
    public com.amalto.webapp.util.webservices.WSConnectorFunction getFunction() {
        return function;
    }
    
    public void setFunction(com.amalto.webapp.util.webservices.WSConnectorFunction function) {
        this.function = function;
    }
    
    public com.amalto.webapp.util.webservices.WSBase64KeyValue[] getParameters() {
        return parameters;
    }
    
    public void setParameters(com.amalto.webapp.util.webservices.WSBase64KeyValue[] parameters) {
        this.parameters = parameters;
    }
}
