// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation £®1.1.2_01£¨±‡“Î∞Ê R40£©
// Generated source version: 1.1.2

package com.amalto.webapp.util.webservices;


public class WSDataCluster {
    protected java.lang.String name;
    protected java.lang.String description;
    protected java.lang.String vocabulary;
    
    public WSDataCluster() {
    }
    
    public WSDataCluster(java.lang.String name, java.lang.String description, java.lang.String vocabulary) {
        this.name = name;
        this.description = description;
        this.vocabulary = vocabulary;
    }
    
    public java.lang.String getName() {
        return name;
    }
    
    public void setName(java.lang.String name) {
        this.name = name;
    }
    
    public java.lang.String getDescription() {
        return description;
    }
    
    public void setDescription(java.lang.String description) {
        this.description = description;
    }
    
    public java.lang.String getVocabulary() {
        return vocabulary;
    }
    
    public void setVocabulary(java.lang.String vocabulary) {
        this.vocabulary = vocabulary;
    }
}
