// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation £®1.1.2_01£¨±‡“Î∞Ê R40£©
// Generated source version: 1.1.2

package com.amalto.webapp.util.webservices;


public class WSExistsSynchronizationItem {
    protected com.amalto.webapp.util.webservices.WSSynchronizationItemPK wsSynchronizationItemPK;
    
    public WSExistsSynchronizationItem() {
    }
    
    public WSExistsSynchronizationItem(com.amalto.webapp.util.webservices.WSSynchronizationItemPK wsSynchronizationItemPK) {
        this.wsSynchronizationItemPK = wsSynchronizationItemPK;
    }
    
    public com.amalto.webapp.util.webservices.WSSynchronizationItemPK getWsSynchronizationItemPK() {
        return wsSynchronizationItemPK;
    }
    
    public void setWsSynchronizationItemPK(com.amalto.webapp.util.webservices.WSSynchronizationItemPK wsSynchronizationItemPK) {
        this.wsSynchronizationItemPK = wsSynchronizationItemPK;
    }
}
