// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation £®1.1.2_01£¨±‡“Î∞Ê R40£©
// Generated source version: 1.1.2

package com.amalto.webapp.util.webservices;


public class WSExistsRoutingOrderV2 {
    protected com.amalto.webapp.util.webservices.WSRoutingOrderV2PK wsRoutingOrderPK;
    
    public WSExistsRoutingOrderV2() {
    }
    
    public WSExistsRoutingOrderV2(com.amalto.webapp.util.webservices.WSRoutingOrderV2PK wsRoutingOrderPK) {
        this.wsRoutingOrderPK = wsRoutingOrderPK;
    }
    
    public com.amalto.webapp.util.webservices.WSRoutingOrderV2PK getWsRoutingOrderPK() {
        return wsRoutingOrderPK;
    }
    
    public void setWsRoutingOrderPK(com.amalto.webapp.util.webservices.WSRoutingOrderV2PK wsRoutingOrderPK) {
        this.wsRoutingOrderPK = wsRoutingOrderPK;
    }
}
