// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation £®1.1.2_01£¨±‡“Î∞Ê R40£©
// Generated source version: 1.1.2

package com.amalto.webapp.util.webservices;


public class WSFindBackgroundJobPKs {
    protected com.amalto.webapp.util.webservices.BackgroundJobStatusType status;
    
    public WSFindBackgroundJobPKs() {
    }
    
    public WSFindBackgroundJobPKs(com.amalto.webapp.util.webservices.BackgroundJobStatusType status) {
        this.status = status;
    }
    
    public com.amalto.webapp.util.webservices.BackgroundJobStatusType getStatus() {
        return status;
    }
    
    public void setStatus(com.amalto.webapp.util.webservices.BackgroundJobStatusType status) {
        this.status = status;
    }
}
