// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation £®1.1.2_01£¨±‡“Î∞Ê R40£©
// Generated source version: 1.1.2

package com.amalto.webapp.util.webservices;


public class WSGetRoutingOrderV2PKsByCriteria {
    protected com.amalto.webapp.util.webservices.WSRoutingOrderV2SearchCriteria wsSearchCriteria;
    
    public WSGetRoutingOrderV2PKsByCriteria() {
    }
    
    public WSGetRoutingOrderV2PKsByCriteria(com.amalto.webapp.util.webservices.WSRoutingOrderV2SearchCriteria wsSearchCriteria) {
        this.wsSearchCriteria = wsSearchCriteria;
    }
    
    public com.amalto.webapp.util.webservices.WSRoutingOrderV2SearchCriteria getWsSearchCriteria() {
        return wsSearchCriteria;
    }
    
    public void setWsSearchCriteria(com.amalto.webapp.util.webservices.WSRoutingOrderV2SearchCriteria wsSearchCriteria) {
        this.wsSearchCriteria = wsSearchCriteria;
    }
}
