// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation £®1.1.2_01£¨±‡“Î∞Ê R40£©
// Generated source version: 1.1.2

package com.amalto.webapp.util.webservices;


public class WSGetBusinessConcepts {
    protected com.amalto.webapp.util.webservices.WSDataModelPK wsDataModelPK;
    
    public WSGetBusinessConcepts() {
    }
    
    public WSGetBusinessConcepts(com.amalto.webapp.util.webservices.WSDataModelPK wsDataModelPK) {
        this.wsDataModelPK = wsDataModelPK;
    }
    
    public com.amalto.webapp.util.webservices.WSDataModelPK getWsDataModelPK() {
        return wsDataModelPK;
    }
    
    public void setWsDataModelPK(com.amalto.webapp.util.webservices.WSDataModelPK wsDataModelPK) {
        this.wsDataModelPK = wsDataModelPK;
    }
}
