// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation £®1.1.2_01£¨±‡“Î∞Ê R40£©
// Generated source version: 1.1.2

package com.amalto.webapp.util.webservices;


public class WSPutItemWithReportArray {
    protected com.amalto.webapp.util.webservices.WSPutItemWithReport[] wsPutItem;
    
    public WSPutItemWithReportArray() {
    }
    
    public WSPutItemWithReportArray(com.amalto.webapp.util.webservices.WSPutItemWithReport[] wsPutItem) {
        this.wsPutItem = wsPutItem;
    }
    
    public com.amalto.webapp.util.webservices.WSPutItemWithReport[] getWsPutItem() {
        return wsPutItem;
    }
    
    public void setWsPutItem(com.amalto.webapp.util.webservices.WSPutItemWithReport[] wsPutItem) {
        this.wsPutItem = wsPutItem;
    }
}
