// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation £®1.1.2_01£¨±‡“Î∞Ê R40£©
// Generated source version: 1.1.2

package com.amalto.webapp.util.webservices;


public class WSPutRole {
    protected com.amalto.webapp.util.webservices.WSRole wsRole;
    
    public WSPutRole() {
    }
    
    public WSPutRole(com.amalto.webapp.util.webservices.WSRole wsRole) {
        this.wsRole = wsRole;
    }
    
    public com.amalto.webapp.util.webservices.WSRole getWsRole() {
        return wsRole;
    }
    
    public void setWsRole(com.amalto.webapp.util.webservices.WSRole wsRole) {
        this.wsRole = wsRole;
    }
}
