// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation £®1.1.2_01£¨±‡“Î∞Ê R40£©
// Generated source version: 1.1.2

package com.amalto.webapp.util.webservices;


public class WSPutItemArray {
    protected com.amalto.webapp.util.webservices.WSPutItem[] wsPutItem;
    
    public WSPutItemArray() {
    }
    
    public WSPutItemArray(com.amalto.webapp.util.webservices.WSPutItem[] wsPutItem) {
        this.wsPutItem = wsPutItem;
    }
    
    public com.amalto.webapp.util.webservices.WSPutItem[] getWsPutItem() {
        return wsPutItem;
    }
    
    public void setWsPutItem(com.amalto.webapp.util.webservices.WSPutItem[] wsPutItem) {
        this.wsPutItem = wsPutItem;
    }
}
