// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation £®1.1.2_01£¨±‡“Î∞Ê R40£©
// Generated source version: 1.1.2

package com.amalto.webapp.util.webservices;


public class WSVersioningItemsVersions {
    protected com.amalto.webapp.util.webservices.WSVersioningItemsVersionsItems[] items;
    
    public WSVersioningItemsVersions() {
    }
    
    public WSVersioningItemsVersions(com.amalto.webapp.util.webservices.WSVersioningItemsVersionsItems[] items) {
        this.items = items;
    }
    
    public com.amalto.webapp.util.webservices.WSVersioningItemsVersionsItems[] getItems() {
        return items;
    }
    
    public void setItems(com.amalto.webapp.util.webservices.WSVersioningItemsVersionsItems[] items) {
        this.items = items;
    }
}
