// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation £®1.1.2_01£¨±‡“Î∞Ê R40£©
// Generated source version: 1.1.2

package com.amalto.webapp.util.webservices;


public class WSVersioningGetItemHistory {
    protected java.lang.String versioningSystemName;
    protected com.amalto.webapp.util.webservices.WSItemPK wsItemPK;
    
    public WSVersioningGetItemHistory() {
    }
    
    public WSVersioningGetItemHistory(java.lang.String versioningSystemName, com.amalto.webapp.util.webservices.WSItemPK wsItemPK) {
        this.versioningSystemName = versioningSystemName;
        this.wsItemPK = wsItemPK;
    }
    
    public java.lang.String getVersioningSystemName() {
        return versioningSystemName;
    }
    
    public void setVersioningSystemName(java.lang.String versioningSystemName) {
        this.versioningSystemName = versioningSystemName;
    }
    
    public com.amalto.webapp.util.webservices.WSItemPK getWsItemPK() {
        return wsItemPK;
    }
    
    public void setWsItemPK(com.amalto.webapp.util.webservices.WSItemPK wsItemPK) {
        this.wsItemPK = wsItemPK;
    }
}
