// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation £®1.1.2_01£¨±‡“Î∞Ê R40£©
// Generated source version: 1.1.2

package com.amalto.webapp.util.webservices;


public class WSVersioningObjectsVersions {
    protected com.amalto.webapp.util.webservices.WSVersioningObjectsVersionsObjects[] objects;
    
    public WSVersioningObjectsVersions() {
    }
    
    public WSVersioningObjectsVersions(com.amalto.webapp.util.webservices.WSVersioningObjectsVersionsObjects[] objects) {
        this.objects = objects;
    }
    
    public com.amalto.webapp.util.webservices.WSVersioningObjectsVersionsObjects[] getObjects() {
        return objects;
    }
    
    public void setObjects(com.amalto.webapp.util.webservices.WSVersioningObjectsVersionsObjects[] objects) {
        this.objects = objects;
    }
}
