// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation £®1.1.2_01£¨±‡“Î∞Ê R40£©
// Generated source version: 1.1.2

package com.amalto.webapp.util.webservices;


public class WSWhereItem {
    protected com.amalto.webapp.util.webservices.WSWhereCondition whereCondition;
    protected com.amalto.webapp.util.webservices.WSWhereAnd whereAnd;
    protected com.amalto.webapp.util.webservices.WSWhereOr whereOr;
    
    public WSWhereItem() {
    }
    
    public WSWhereItem(com.amalto.webapp.util.webservices.WSWhereCondition whereCondition, com.amalto.webapp.util.webservices.WSWhereAnd whereAnd, com.amalto.webapp.util.webservices.WSWhereOr whereOr) {
        this.whereCondition = whereCondition;
        this.whereAnd = whereAnd;
        this.whereOr = whereOr;
    }
    
    public com.amalto.webapp.util.webservices.WSWhereCondition getWhereCondition() {
        return whereCondition;
    }
    
    public void setWhereCondition(com.amalto.webapp.util.webservices.WSWhereCondition whereCondition) {
        this.whereCondition = whereCondition;
    }
    
    public com.amalto.webapp.util.webservices.WSWhereAnd getWhereAnd() {
        return whereAnd;
    }
    
    public void setWhereAnd(com.amalto.webapp.util.webservices.WSWhereAnd whereAnd) {
        this.whereAnd = whereAnd;
    }
    
    public com.amalto.webapp.util.webservices.WSWhereOr getWhereOr() {
        return whereOr;
    }
    
    public void setWhereOr(com.amalto.webapp.util.webservices.WSWhereOr whereOr) {
        this.whereOr = whereOr;
    }
}
