/*
 * Generated by XDoclet - Do not edit!
 */
package com.amalto.core.plugin.base.version.ejb.local;

/**
 * Local interface for VersionTransformerPlugin.
 * @xdoclet-generated at 15-01-08
 * @copyright The XDoclet Team
 * @author XDoclet
 * @version ${version}
 */
public interface VersionTransformerPluginLocal
   extends javax.ejb.EJBLocalObject, com.amalto.core.objects.transformers.v2.util.TransformerPluginV2LocalInterface
{

}
