/*
 * Generated by XDoclet - Do not edit!
 */
package com.amalto.core.objects.routing.v2.ejb.remote;

/**
 * Remote interface for RoutingEngineV2Ctrl.
 * @xdoclet-generated
 * @copyright The XDoclet Team
 * @author XDoclet
 * @version ${version}
 */
public interface RoutingEngineV2Ctrl
   extends javax.ejb.EJBObject
{
   /**
    * Routes a document
    * @return the list of routing rules PKs that matched
    * @throws XtentisException
    */
   public com.amalto.core.objects.routing.v2.ejb.RoutingRulePOJOPK[] route( com.amalto.core.ejb.ItemPOJOPK itemPOJOPK )
      throws com.amalto.core.util.XtentisException, java.rmi.RemoteException;

   /**
    * Starts/restarts the router
    * @throws XtentisException
    */
   public void start(  )
      throws com.amalto.core.util.XtentisException, java.rmi.RemoteException;

   /**
    * Stops the routing queue
    * @throws XtentisException
    */
   public void stop(  )
      throws com.amalto.core.util.XtentisException, java.rmi.RemoteException;

   /**
    * Toggle suspend a routing queue
    * @throws XtentisException
    */
   public void suspend( boolean suspend )
      throws com.amalto.core.util.XtentisException, java.rmi.RemoteException;

   /**
    * Toggle suspend a routing queue
    * @throws XtentisException
    */
   public int getStatus(  )
      throws com.amalto.core.util.XtentisException, java.rmi.RemoteException;

}
