/*
 * Generated by XDoclet - Do not edit!
 */
package com.amalto.core.plugin.base.csvparser.ejb.local;

/**
 * Local home interface for CSVParserTransformerPlugin.
 * @xdoclet-generated at 18-11-09
 * @copyright The XDoclet Team
 * @author XDoclet
 * @version ${version}
 */
public interface CSVParserTransformerPluginLocalHome
   extends javax.ejb.EJBLocalHome
{
   public static final String COMP_NAME="java:comp/env/ejb/CSVParserTransformerPluginLocal";
   public static final String JNDI_NAME="amalto/local/transformer/plugin/csvparser";

   public com.amalto.core.plugin.base.csvparser.ejb.local.CSVParserTransformerPluginLocal create()
      throws javax.ejb.CreateException;

}
