/*
 * Generated by XDoclet - Do not edit!
 */
package com.amalto.service.workflow.ejb.local;

/**
 * Session layer for Workflow.
 * @xdoclet-generated at 8-12-09
 * @copyright The XDoclet Team
 * @author XDoclet
 * @version ${version}
 */
public class WorkflowSession
   extends com.amalto.service.workflow.ejb.WorkflowBean
   implements javax.ejb.SessionBean, com.amalto.core.ejb.WorkflowServiceCtrlLocalBI
{
   public void ejbActivate() 
   {

   }

   public void ejbPassivate() 
   {
   }

   public void setSessionContext(javax.ejb.SessionContext ctx) 
   {
   }

   public void unsetSessionContext() 
   {
   }

   public void ejbRemove() 
   {
   }

   public void ejbCreate() throws javax.ejb.CreateException
   {
   }

}
