/*
 * Generated by XDoclet - Do not edit!
 */
package com.amalto.service.workflow.ejb.local;

/**
 * Local interface for Workflow.
 * @xdoclet-generated at 2-12-09
 * @copyright The XDoclet Team
 * @author XDoclet
 * @version ${version}
 */
public interface WorkflowLocal
   extends javax.ejb.EJBLocalObject, com.amalto.core.ejb.WorkflowServiceCtrlLocalBI
{

}
