<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="mdmproperties"
    nsURI="http://www.talend.org/mdmproperties" nsPrefix="mdmproperties">
  <eClassifiers xsi:type="ecore:EClass" name="MDMItem" eSuperTypes="../../org.talend.model/model/properties.ecore#//Item"/>
  <eClassifiers xsi:type="ecore:EClass" name="MDMServerDefItem" eSuperTypes="#//MDMItem">
    <eStructuralFeatures xsi:type="ecore:EReference" name="serverDef" eType="ecore:EClass MDMMetadata.ecore#//MDMServerDef"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MDMServerObjectItem" eSuperTypes="#//MDMItem">
    <eOperations name="getMDMServerObject" eType="ecore:EClass MDMServerObject.ecore#//MDMServerObject"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="WSMenuItem" eSuperTypes="#//MDMServerObjectItem">
    <eStructuralFeatures xsi:type="ecore:EReference" name="wsMenu" eType="ecore:EClass MDMServerObject.ecore#//WSMenuE"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="WSRoleItem" eSuperTypes="#//MDMServerObjectItem">
    <eStructuralFeatures xsi:type="ecore:EReference" name="wsRole" eType="ecore:EClass MDMServerObject.ecore#//WSRoleE"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ContainerItem" eSuperTypes="#//MDMItem">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="label" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="repObjType" eType="#//ERepositoryObjectType"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" eType="#//ContainerType"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="ERepositoryObjectType" instanceClassName="org.talend.core.model.repository.ERepositoryObjectType"/>
  <eClassifiers xsi:type="ecore:EEnum" name="ContainerType">
    <eLiterals name="CATEGORY"/>
    <eLiterals name="SYSTEM_FOLDER" value="2"/>
    <eLiterals name="FOLDER" value="1"/>
  </eClassifiers>
</ecore:EPackage>
