<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="mdmproperties"
    nsURI="http://www.talend.org/mdmproperties" nsPrefix="mdmproperties">
  <eClassifiers xsi:type="ecore:EClass" name="MDMItem" eSuperTypes="../../org.talend.model/model/properties.ecore#//Item"/>
  <eClassifiers xsi:type="ecore:EClass" name="MDMServerDefItem" eSuperTypes="#//MDMItem">
    <eStructuralFeatures xsi:type="ecore:EReference" name="serverDef" eType="ecore:EClass MDMMetadata.ecore#//MDMServerDef"/>
  </eClassifiers>
</ecore:EPackage>
