<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="mdmserverobject"
    nsURI="http://www.talend.org/mdmserverobject" nsPrefix="mdmserverobject">
  <eClassifiers xsi:type="ecore:EClass" name="MDMServerObject">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="description" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="system" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="lastServerDef" eType="ecore:EClass MDMMetadata.ecore#//MDMServerDef"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="WSMenuE" eSuperTypes="#//MDMServerObject">
    <eStructuralFeatures xsi:type="ecore:EReference" name="menuEntries" upperBound="-1"
        eType="#//WSMenuEntryE" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="WSMenuEntryE">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="application" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="context" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="icon" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="descriptions" upperBound="-1"
        eType="#//WSMenuMenuEntriesDescriptionsE" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="subMenus" upperBound="-1"
        eType="#//WSMenuEntryE" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="WSMenuMenuEntriesDescriptionsE">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="language" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="label" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="WSRoleE" eSuperTypes="#//MDMServerObject">
    <eStructuralFeatures xsi:type="ecore:EReference" name="specification" upperBound="-1"
        eType="#//WSRoleSpecificationE" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="WSRoleSpecificationE">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="admin" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="objectType" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="instance" upperBound="-1"
        eType="#//WSRoleSpecificationInstanceE" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="WSRoleSpecificationInstanceE">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="instanceName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="writable" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="parameter" eType="#//StringArray"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="StringArray" instanceClassName="java.lang.String[]"/>
  <eClassifiers xsi:type="ecore:EClass" name="WSViewE" eSuperTypes="#//MDMServerObject">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="searchableBusinessElements"
        eType="#//StringArray"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="viewableBusinessElements"
        eType="#//StringArray"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="transformerActive" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="whereConditions" upperBound="-1"
        eType="#//WSWhereConditionE" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="WSWhereConditionE">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="leftPath" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="rightValueOrPath" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="stringPredicate" eType="#//WSStringPredicateE"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="operator" eType="#//WSWhereOperatorE"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="WSWhereOperatorE"/>
  <eClassifiers xsi:type="ecore:EClass" name="WSStringPredicateE"/>
</ecore:EPackage>
