/*
 * Generated by XDoclet - Do not edit!
 */
package com.amalto.core.plugin.base.batchproject.ejb.local;

/**
 * Session layer for BatchProjectPlugin.
 * @xdoclet-generated at 18-11-09
 * @copyright The XDoclet Team
 * @author XDoclet
 * @version ${version}
 */
public class BatchProjectPluginSession
   extends com.amalto.core.plugin.base.batchproject.ejb.BatchProjectTransformerPluginBean
   implements javax.ejb.SessionBean, com.amalto.core.objects.transformers.v2.util.TransformerPluginV2LocalInterface
{
   public void ejbActivate() 
   {

   }

   public void ejbPassivate() 
   {
   }

   public void setSessionContext(javax.ejb.SessionContext ctx) 
   {
   }

   public void unsetSessionContext() 
   {
   }

   public void ejbRemove() 
   {
   }

   public void ejbCreate() throws javax.ejb.CreateException
   {
   }

}
