// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation £®1.1.2_01£¨±‡“Î∞Ê R40£©
// Generated source version: 1.1.2

package com.amalto.webapp.util.webservices;


public class WSDataClusterPKArray {
    protected com.amalto.webapp.util.webservices.WSDataClusterPK[] wsDataClusterPKs;
    
    public WSDataClusterPKArray() {
    }
    
    public WSDataClusterPKArray(com.amalto.webapp.util.webservices.WSDataClusterPK[] wsDataClusterPKs) {
        this.wsDataClusterPKs = wsDataClusterPKs;
    }
    
    public com.amalto.webapp.util.webservices.WSDataClusterPK[] getWsDataClusterPKs() {
        return wsDataClusterPKs;
    }
    
    public void setWsDataClusterPKs(com.amalto.webapp.util.webservices.WSDataClusterPK[] wsDataClusterPKs) {
        this.wsDataClusterPKs = wsDataClusterPKs;
    }
}
