// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation £®1.1.2_01£¨±‡“Î∞Ê R40£©
// Generated source version: 1.1.2

package com.amalto.webapp.util.webservices;


public class WSPutItemWithReport {
    protected com.amalto.webapp.util.webservices.WSPutItem wsPutItem;
    protected java.lang.String source;
    protected java.lang.String operationType;
    protected com.amalto.webapp.util.webservices.WSUpdateReportItemArray wsUpdateReportItemArray;
    
    public WSPutItemWithReport() {
    }
    
    public WSPutItemWithReport(com.amalto.webapp.util.webservices.WSPutItem wsPutItem, java.lang.String source, java.lang.String operationType, com.amalto.webapp.util.webservices.WSUpdateReportItemArray wsUpdateReportItemArray) {
        this.wsPutItem = wsPutItem;
        this.source = source;
        this.operationType = operationType;
        this.wsUpdateReportItemArray = wsUpdateReportItemArray;
    }
    
    public com.amalto.webapp.util.webservices.WSPutItem getWsPutItem() {
        return wsPutItem;
    }
    
    public void setWsPutItem(com.amalto.webapp.util.webservices.WSPutItem wsPutItem) {
        this.wsPutItem = wsPutItem;
    }
    
    public java.lang.String getSource() {
        return source;
    }
    
    public void setSource(java.lang.String source) {
        this.source = source;
    }
    
    public java.lang.String getOperationType() {
        return operationType;
    }
    
    public void setOperationType(java.lang.String operationType) {
        this.operationType = operationType;
    }
    
    public com.amalto.webapp.util.webservices.WSUpdateReportItemArray getWsUpdateReportItemArray() {
        return wsUpdateReportItemArray;
    }
    
    public void setWsUpdateReportItemArray(com.amalto.webapp.util.webservices.WSUpdateReportItemArray wsUpdateReportItemArray) {
        this.wsUpdateReportItemArray = wsUpdateReportItemArray;
    }
}
