// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation £®1.1.2_01£¨±‡“Î∞Ê R40£©
// Generated source version: 1.1.2

package com.amalto.webapp.util.webservices;


public class WSRemoveDroppedItem {
    protected com.amalto.webapp.util.webservices.WSDroppedItemPK wsDroppedItemPK;
    
    public WSRemoveDroppedItem() {
    }
    
    public WSRemoveDroppedItem(com.amalto.webapp.util.webservices.WSDroppedItemPK wsDroppedItemPK) {
        this.wsDroppedItemPK = wsDroppedItemPK;
    }
    
    public com.amalto.webapp.util.webservices.WSDroppedItemPK getWsDroppedItemPK() {
        return wsDroppedItemPK;
    }
    
    public void setWsDroppedItemPK(com.amalto.webapp.util.webservices.WSDroppedItemPK wsDroppedItemPK) {
        this.wsDroppedItemPK = wsDroppedItemPK;
    }
}
