// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation £®1.1.2_01£¨±‡“Î∞Ê R40£©
// Generated source version: 1.1.2

package com.amalto.webapp.util.webservices;


public class WSRoutingRule {
    protected java.lang.String name;
    protected java.lang.String description;
    protected boolean synchronous;
    protected java.lang.String concept;
    protected java.lang.String serviceJNDI;
    protected java.lang.String parameters;
    protected com.amalto.webapp.util.webservices.WSRoutingRuleExpression[] wsRoutingRuleExpressions;
    protected java.lang.String condition;
    protected java.lang.Boolean deactive;
    
    public WSRoutingRule() {
    }
    
    public WSRoutingRule(java.lang.String name, java.lang.String description, boolean synchronous, java.lang.String concept, java.lang.String serviceJNDI, java.lang.String parameters, com.amalto.webapp.util.webservices.WSRoutingRuleExpression[] wsRoutingRuleExpressions, java.lang.String condition, java.lang.Boolean deactive) {
        this.name = name;
        this.description = description;
        this.synchronous = synchronous;
        this.concept = concept;
        this.serviceJNDI = serviceJNDI;
        this.parameters = parameters;
        this.wsRoutingRuleExpressions = wsRoutingRuleExpressions;
        this.condition = condition;
        this.deactive = deactive;
    }
    
    public java.lang.String getName() {
        return name;
    }
    
    public void setName(java.lang.String name) {
        this.name = name;
    }
    
    public java.lang.String getDescription() {
        return description;
    }
    
    public void setDescription(java.lang.String description) {
        this.description = description;
    }
    
    public boolean isSynchronous() {
        return synchronous;
    }
    
    public void setSynchronous(boolean synchronous) {
        this.synchronous = synchronous;
    }
    
    public java.lang.String getConcept() {
        return concept;
    }
    
    public void setConcept(java.lang.String concept) {
        this.concept = concept;
    }
    
    public java.lang.String getServiceJNDI() {
        return serviceJNDI;
    }
    
    public void setServiceJNDI(java.lang.String serviceJNDI) {
        this.serviceJNDI = serviceJNDI;
    }
    
    public java.lang.String getParameters() {
        return parameters;
    }
    
    public void setParameters(java.lang.String parameters) {
        this.parameters = parameters;
    }
    
    public com.amalto.webapp.util.webservices.WSRoutingRuleExpression[] getWsRoutingRuleExpressions() {
        return wsRoutingRuleExpressions;
    }
    
    public void setWsRoutingRuleExpressions(com.amalto.webapp.util.webservices.WSRoutingRuleExpression[] wsRoutingRuleExpressions) {
        this.wsRoutingRuleExpressions = wsRoutingRuleExpressions;
    }
    
    public java.lang.String getCondition() {
        return condition;
    }
    
    public void setCondition(java.lang.String condition) {
        this.condition = condition;
    }
    
    public java.lang.Boolean getDeactive() {
        return deactive;
    }
    
    public void setDeactive(java.lang.Boolean deactive) {
        this.deactive = deactive;
    }
}
