// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation £®1.1.2_01£¨±‡“Î∞Ê R40£©
// Generated source version: 1.1.2

package com.amalto.webapp.util.webservices;


public class WSSynchronizationItem {
    protected com.amalto.webapp.util.webservices.WSItemPK wsItemPK;
    protected java.lang.String localRevisionID;
    protected java.lang.String lastRunPlan;
    protected com.amalto.webapp.util.webservices.WSSynchronizationItemStatus status;
    protected java.lang.String resolvedProjection;
    protected com.amalto.webapp.util.webservices.WSSynchronizationItemRemoteInstances[] remoteInstances;
    
    public WSSynchronizationItem() {
    }
    
    public WSSynchronizationItem(com.amalto.webapp.util.webservices.WSItemPK wsItemPK, java.lang.String localRevisionID, java.lang.String lastRunPlan, com.amalto.webapp.util.webservices.WSSynchronizationItemStatus status, java.lang.String resolvedProjection, com.amalto.webapp.util.webservices.WSSynchronizationItemRemoteInstances[] remoteInstances) {
        this.wsItemPK = wsItemPK;
        this.localRevisionID = localRevisionID;
        this.lastRunPlan = lastRunPlan;
        this.status = status;
        this.resolvedProjection = resolvedProjection;
        this.remoteInstances = remoteInstances;
    }
    
    public com.amalto.webapp.util.webservices.WSItemPK getWsItemPK() {
        return wsItemPK;
    }
    
    public void setWsItemPK(com.amalto.webapp.util.webservices.WSItemPK wsItemPK) {
        this.wsItemPK = wsItemPK;
    }
    
    public java.lang.String getLocalRevisionID() {
        return localRevisionID;
    }
    
    public void setLocalRevisionID(java.lang.String localRevisionID) {
        this.localRevisionID = localRevisionID;
    }
    
    public java.lang.String getLastRunPlan() {
        return lastRunPlan;
    }
    
    public void setLastRunPlan(java.lang.String lastRunPlan) {
        this.lastRunPlan = lastRunPlan;
    }
    
    public com.amalto.webapp.util.webservices.WSSynchronizationItemStatus getStatus() {
        return status;
    }
    
    public void setStatus(com.amalto.webapp.util.webservices.WSSynchronizationItemStatus status) {
        this.status = status;
    }
    
    public java.lang.String getResolvedProjection() {
        return resolvedProjection;
    }
    
    public void setResolvedProjection(java.lang.String resolvedProjection) {
        this.resolvedProjection = resolvedProjection;
    }
    
    public com.amalto.webapp.util.webservices.WSSynchronizationItemRemoteInstances[] getRemoteInstances() {
        return remoteInstances;
    }
    
    public void setRemoteInstances(com.amalto.webapp.util.webservices.WSSynchronizationItemRemoteInstances[] remoteInstances) {
        this.remoteInstances = remoteInstances;
    }
}
