// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation £®1.1.2_01£¨±‡“Î∞Ê R40£©
// Generated source version: 1.1.2

package com.amalto.webapp.util.webservices;


public class WSWhereAnd {
    protected com.amalto.webapp.util.webservices.WSWhereItem[] whereItems;
    
    public WSWhereAnd() {
    }
    
    public WSWhereAnd(com.amalto.webapp.util.webservices.WSWhereItem[] whereItems) {
        this.whereItems = whereItems;
    }
    
    public com.amalto.webapp.util.webservices.WSWhereItem[] getWhereItems() {
        return whereItems;
    }
    
    public void setWhereItems(com.amalto.webapp.util.webservices.WSWhereItem[] whereItems) {
        this.whereItems = whereItems;
    }
}
