/*
 * Generated by XDoclet - Do not edit!
 */
package com.amalto.service.logging.ejb.local;

/**
 * Session layer for Logging.
 * @xdoclet-generated at 27-09-09
 * @copyright The XDoclet Team
 * @author XDoclet
 * @version ${version}
 */
public class LoggingSession
   extends com.amalto.service.logging.ejb.LoggingServiceBean
   implements javax.ejb.SessionBean
{
   public void ejbActivate() 
   {

   }

   public void ejbPassivate() 
   {
   }

   public void setSessionContext(javax.ejb.SessionContext ctx) 
   {
   }

   public void unsetSessionContext() 
   {
   }

   public void ejbRemove() 
   {
   }

   public void ejbCreate() throws javax.ejb.CreateException
   {
   }

}
