/*
 * Generated by XDoclet - Do not edit!
 */
package com.amalto.core.ejb.local;

/**
 * Local home interface for TransformerPluginCtrl.
 * @deprecated - use TransformerV2 package
 * @xdoclet-generated at 13-08-09
 * @copyright The XDoclet Team
 * @author XDoclet
 * @version ${version}
 */
public interface TransformerPluginCtrlLocalHome
   extends javax.ejb.EJBLocalHome
{

}
