
package talend.core.transformer.plugin.v2.tiscall.webservices;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.1-b03-
 * Generated source version: 2.0
 * 
 */
@WebServiceClient(name = "WSxmlService", targetNamespace = "http://talend.org", wsdlLocation = "http://localhost:8083/WSxml_0.1/services/WSxml?WSDL")
public class WSxmlService
    extends Service
{

    private final static URL WSXMLSERVICE_WSDL_LOCATION;

    static {
        URL url = null;
        try {
            url = new URL("http://localhost:8083/WSxml_0.1/services/WSxml?WSDL");
        } catch (MalformedURLException e) {
            e.printStackTrace();
        }
        WSXMLSERVICE_WSDL_LOCATION = url;
    }

    public WSxmlService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public WSxmlService() {
        super(WSXMLSERVICE_WSDL_LOCATION, new QName("http://talend.org", "WSxmlService"));
    }

    /**
     * 
     * @return
     *     returns WSxml
     */
    @WebEndpoint(name = "WSxml")
    public WSxml getWSxml() {
        return (WSxml)super.getPort(new QName("http://talend.org", "WSxml"), WSxml.class);
    }

}
