package urn_com_amalto_xtentis_webservice;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.2.5
 * Thu Nov 19 17:39:24 CST 2009
 * Generated source version: 2.2.5
 * 
 */
 
@WebService(targetNamespace = "urn-com-amalto-xtentis-webservice", name = "XtentisPort")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface XtentisPort {

    @WebResult(name = "WSMenuPK", targetNamespace = "urn-com-amalto-xtentis-webservice", partName = "wsMenuPK")
    @WebMethod
    public WSMenuPK deleteMenu(
        @WebParam(partName = "wsMenuDelete", name = "WSDeleteMenu", targetNamespace = "urn-com-amalto-xtentis-webservice")
        WSDeleteMenu wsMenuDelete
    );

    @WebResult(name = "WSBoolean", targetNamespace = "urn-com-amalto-xtentis-webservice", partName = "wsBoolean")
    @WebMethod
    public WSBoolean existsTransformerV2(
        @WebParam(partName = "wsExistsTransformerV2", name = "WSExistsTransformerV2", targetNamespace = "urn-com-amalto-xtentis-webservice")
        WSExistsTransformerV2 wsExistsTransformerV2
    );

    @WebResult(name = "WSString", targetNamespace = "urn-com-amalto-xtentis-webservice", partName = "versioningSystemName")
    @WebMethod
    public WSString putVersioningSystemConfiguration(
        @WebParam(partName = "wsPutVersioningSystemConfiguration", name = "WSPutVersioningSystemConfiguration", targetNamespace = "urn-com-amalto-xtentis-webservice")
        WSPutVersioningSystemConfiguration wsPutVersioningSystemConfiguration
    );

    @WebResult(name = "WSVersioningObjectsVersions", targetNamespace = "urn-com-amalto-xtentis-webservice", partName = "wsVersioningObjectsVersions")
    @WebMethod
    public WSVersioningObjectsVersions versioningGetObjectsVersions(
        @WebParam(partName = "wsVersioningGetObjectsVersions", name = "WSVersioningGetObjectsVersions", targetNamespace = "urn-com-amalto-xtentis-webservice")
        WSVersioningGetObjectsVersions wsVersioningGetObjectsVersions
    );

    @WebResult(name = "WSMenuPKArray", targetNamespace = "urn-com-amalto-xtentis-webservice", partName = "wsMenuPKArray")
    @WebMethod
    public WSMenuPKArray getMenuPKs(
        @WebParam(partName = "regex", name = "WSGetMenuPKs", targetNamespace = "urn-com-amalto-xtentis-webservice")
        WSGetMenuPKs regex
    );

    @WebResult(name = "WSSynchronizationPlanPK", targetNamespace = "urn-com-amalto-xtentis-webservice", partName = "wsSynchronizationPlanPK")
    @WebMethod
    public WSSynchronizationPlanPK putSynchronizationPlan(
        @WebParam(partName = "wsSynchronizationPlan", name = "WSPutSynchronizationPlan", targetNamespace = "urn-com-amalto-xtentis-webservice")
        WSPutSynchronizationPlan wsSynchronizationPlan
    );

    @WebResult(name = "WSPipeline", targetNamespace = "urn-com-amalto-xtentis-webservice", partName = "wsPipeline")
    @WebMethod
    public WSPipeline processBytesUsingTransformer(
        @WebParam(partName = "wsProcessBytesUsingTransformer", name = "WSProcessBytesUsingTransformer", targetNamespace = "urn-com-amalto-xtentis-webservice")
        WSProcessBytesUsingTransformer wsProcessBytesUsingTransformer
    );

    @WebResult(name = "WSSynchronizationItem", targetNamespace = "urn-com-amalto-xtentis-webservice", partName = "wsSynchronizationItem")
    @WebMethod
    public WSSynchronizationItem resolveSynchronizationItem(
        @WebParam(partName = "wsResolveSynchronizationItem", name = "WSResolveSynchronizationItem", targetNamespace = "urn-com-amalto-xtentis-webservice")
        WSResolveSynchronizationItem wsResolveSynchronizationItem
    );

    @WebResult(name = "WSStringArray", targetNamespace = "urn-com-amalto-xtentis-webservice", partName = "wsSynchronizationPlanObjectNames")
    @WebMethod
    public WSStringArray getObjectsForSynchronizationPlans(
        @WebParam(partName = "regex", name = "WSGetObjectsForSynchronizationPlans", targetNamespace = "urn-com-amalto-xtentis-webservice")
        WSGetObjectsForSynchronizationPlans regex
    );

    @WebResult(name = "WSBackgroundJobPK", targetNamespace = "urn-com-amalto-xtentis-webservice", partName = "wsBackgroundJobPK")
    @WebMethod
    public WSBackgroundJobPK versioningTagItems(
        @WebParam(partName = "wsVersioningTagItems", name = "WSVersioningTagItems", targetNamespace = "urn-com-amalto-xtentis-webservice")
        WSVersioningTagItems wsVersioningTagItems
    );

    @WebResult(name = "WSTransformer", targetNamespace = "urn-com-amalto-xtentis-webservice", partName = "wsTransformer")
    @WebMethod
    public WSTransformer getTransformer(
        @WebParam(partName = "wsGetTransformer", name = "WSGetTransformer", targetNamespace = "urn-com-amalto-xtentis-webservice")
        WSGetTransformer wsGetTransformer
    );

    @WebResult(name = "WSRoutingOrderV2PK", targetNamespace = "urn-com-amalto-xtentis-webservice", partName = "wsRoutingOrderPK")
    @WebMethod
    public WSRoutingOrderV2PK executeRoutingOrderV2Asynchronously(
        @WebParam(partName = "wsExecuteRoutingOrderAsynchronously", name = "WSExecuteRoutingOrderV2Asynchronously", targetNamespace = "urn-com-amalto-xtentis-webservice")
        WSExecuteRoutingOrderV2Asynchronously wsExecuteRoutingOrderAsynchronously
    );

    @WebResult(name = "WSRoutingRulePKArray", targetNamespace = "urn-com-amalto-xtentis-webservice", partName = "wsRoutingRulePKs")
    @WebMethod
    public WSRoutingRulePKArray routeItemV2(
        @WebParam(partName = "wsRouteItem", name = "WSRouteItemV2", targetNamespace = "urn-com-amalto-xtentis-webservice")
        WSRouteItemV2 wsRouteItem
    );

    @WebResult(name = "WSString", targetNamespace = "urn-com-amalto-xtentis-webservice", partName = "result")
    @WebMethod
    public WSString putServiceConfiguration(
        @WebParam(partName = "wsPutConfiguration", name = "WSServicePutConfiguration", targetNamespace = "urn-com-amalto-xtentis-webservice")
        WSServicePutConfiguration wsPutConfiguration
    );

    @WebResult(name = "WSDataCluster", targetNamespace = "urn-com-amalto-xtentis-webservice", partName = "wsDataCluster")
    @WebMethod
    public WSDataCluster getDataCluster(
        @WebParam(partName = "wsDataClusterPK", name = "WSGetDataCluster", targetNamespace = "urn-com-amalto-xtentis-webservice")
        WSGetDataCluster wsDataClusterPK
    );

    @WebResult(name = "WSBoolean", targetNamespace = "urn-com-amalto-xtentis-webservice", partName = "wsBoolean")
    @WebMethod
    public WSBoolean existsTransformerPluginV2(
        @WebParam(partName = "wsExistsTransformerPluginV2", name = "WSExistsTransformerPluginV2", targetNamespace = "urn-com-amalto-xtentis-webservice")
        WSExistsTransformerPluginV2 wsExistsTransformerPluginV2
    );

    @WebResult(name = "WSDataClusterPK", targetNamespace = "urn-com-amalto-xtentis-webservice", partName = "wsDataClusterPK")
    @WebMethod
    public WSDataClusterPK putDataCluster(
        @WebParam(partName = "wsDataCluster", name = "WSPutDataCluster", targetNamespace = "urn-com-amalto-xtentis-webservice")
        WSPutDataCluster wsDataCluster
    );

    @WebResult(name = "WSStoredProcedurePKArray", targetNamespace = "urn-com-amalto-xtentis-webservice", partName = "wsStoredProcedurePKArray")
    @WebMethod
    public WSStoredProcedurePKArray getStoredProcedurePKs(
        @WebParam(partName = "regex", name = "WSRegexStoredProcedure", targetNamespace = "urn-com-amalto-xtentis-webservice")
        WSRegexStoredProcedure regex
    );

    @WebResult(name = "WSStoredProcedurePK", targetNamespace = "urn-com-amalto-xtentis-webservice", partName = "wsStoredProcedurePK")
    @WebMethod
    public WSStoredProcedurePK deleteStoredProcedure(
        @WebParam(partName = "wsStoredProcedureDelete", name = "WSDeleteStoredProcedure", targetNamespace = "urn-com-amalto-xtentis-webservice")
        WSDeleteStoredProcedure wsStoredProcedureDelete
    );

    @WebResult(name = "WSPipeline", targetNamespace = "urn-com-amalto-xtentis-webservice", partName = "wsPipeline")
    @WebMethod
    public WSPipeline extractUsingTransformer(
        @WebParam(partName = "wsExtractUsingTransformer", name = "WSExtractUsingTransformer", targetNamespace = "urn-com-amalto-xtentis-webservice")
        WSExtractUsingTransformer wsExtractUsingTransformer
    );

    @WebResult(name = "WSDataClusterPK", targetNamespace = "urn-com-amalto-xtentis-webservice", partName = "wsDataClusterPK")
    @WebMethod
    public WSDataClusterPK deleteDataCluster(
        @WebParam(partName = "wsDeleteDataCluster", name = "WSDeleteDataCluster", targetNamespace = "urn-com-amalto-xtentis-webservice")
        WSDeleteDataCluster wsDeleteDataCluster
    );

    @WebResult(name = "WSString", targetNamespace = "urn-com-amalto-xtentis-webservice", partName = "count")
    @WebMethod
    public WSString count(
        @WebParam(partName = "wsCount", name = "WSCount", targetNamespace = "urn-com-amalto-xtentis-webservice")
        WSCount wsCount
    );

    @WebResult(name = "WSStringArray", targetNamespace = "urn-com-amalto-xtentis-webservice", partName = "wsSynchronizationPlanAlgorithmNames")
    @WebMethod
    public WSStringArray getSynchronizationPlanItemsAlgorithms(
        @WebParam(partName = "regex", name = "WSGetSynchronizationPlanItemsAlgorithms", targetNamespace = "urn-com-amalto-xtentis-webservice")
        WSGetSynchronizationPlanItemsAlgorithms regex
    );

    @WebResult(name = "WSConnectorInteractionResponse", targetNamespace = "urn-com-amalto-xtentis-webservice", partName = "wsConnectorInteractionResponse")
    @WebMethod
    public WSConnectorInteractionResponse connectorInteraction(
        @WebParam(partName = "wsConnectorInteraction", name = "WSConnectorInteraction", targetNamespace = "urn-com-amalto-xtentis-webservice")
        WSConnectorInteraction wsConnectorInteraction
    );

    @WebResult(name = "WSString", targetNamespace = "urn-com-amalto-xtentis-webservice", partName = "value")
    @WebMethod
    public WSString getBusinessConceptValue(
        @WebParam(partName = "wsGetBusinessConceptValue", name = "WSGetBusinessConceptValue", targetNamespace = "urn-com-amalto-xtentis-webservice")
        WSGetBusinessConceptValue wsGetBusinessConceptValue
    );

    @WebResult(name = "WSRoutingOrderV2PK", targetNamespace = "urn-com-amalto-xtentis-webservice", partName = "wsRoutingOrderPK")
    @WebMethod
    public WSRoutingOrderV2PK deleteRoutingOrderV2(
        @WebParam(partName = "wsDeleteRoutingOrder", name = "WSDeleteRoutingOrderV2", targetNamespace = "urn-com-amalto-xtentis-webservice")
        WSDeleteRoutingOrderV2 wsDeleteRoutingOrder
    );

    @WebResult(name = "WSDataClusterPKArray", targetNamespace = "urn-com-amalto-xtentis-webservice", partName = "wsDataClusterPKs")
    @WebMethod
    public WSDataClusterPKArray getDataClusterPKs(
        @WebParam(partName = "regexp", name = "WSRegexDataClusterPKs", targetNamespace = "urn-com-amalto-xtentis-webservice")
        WSRegexDataClusterPKs regexp
    );

    @WebResult(name = "WSSynchronizationPlanStatus", targetNamespace = "urn-com-amalto-xtentis-webservice", partName = "wsSynchronizationPlanStatus")
    @WebMethod
    public WSSynchronizationPlanStatus synchronizationPlanAction(
        @WebParam(partName = "wsSynchronizationPlanAction", name = "WSSynchronizationPlanAction", targetNamespace = "urn-com-amalto-xtentis-webservice")
        WSSynchronizationPlanAction wsSynchronizationPlanAction
    );

    @WebResult(name = "WSVersioningItemHistory", targetNamespace = "urn-com-amalto-xtentis-webservice", partName = "wsVersioningItemHistory")
    @WebMethod
    public WSVersioningItemHistory versioningGetItemHistory(
        @WebParam(partName = "wsVersioningGetItemHistory", name = "WSVersioningGetItemHistory", targetNamespace = "urn-com-amalto-xtentis-webservice")
        WSVersioningGetItemHistory wsVersioningGetItemHistory
    );

    @WebResult(name = "WSBoolean", targetNamespace = "urn-com-amalto-xtentis-webservice", partName = "wsBooelan")
    @WebMethod
    public WSBoolean existsView(
        @WebParam(partName = "wsViewPK", name = "WSExistsView", targetNamespace = "urn-com-amalto-xtentis-webservice")
        WSExistsView wsViewPK
    );

    @WebResult(name = "WSString", targetNamespace = "urn-com-amalto-xtentis-webservice", partName = "wsBusinessConceptName")
    @WebMethod
    public WSString deleteBusinessConcept(
        @WebParam(partName = "wsDeleteBusinessConcept", name = "WSDeleteBusinessConcept", targetNamespace = "urn-com-amalto-xtentis-webservice")
        WSDeleteBusinessConcept wsDeleteBusinessConcept
    );

    @WebResult(name = "WSDroppedItemPKArray", targetNamespace = "urn-com-amalto-xtentis-webservice", partName = "wsDroppedItemPKArray")
    @WebMethod
    public WSDroppedItemPKArray findAllDroppedItemsPKs(
        @WebParam(partName = "regex", name = "WSFindAllDroppedItemsPKs", targetNamespace = "urn-com-amalto-xtentis-webservice")
        WSFindAllDroppedItemsPKs regex
    );

    @WebResult(name = "WSMenu", targetNamespace = "urn-com-amalto-xtentis-webservice", partName = "wsMenu")
    @WebMethod
    public WSMenu getMenu(
        @WebParam(partName = "wsGetMenu", name = "WSGetMenu", targetNamespace = "urn-com-amalto-xtentis-webservice")
        WSGetMenu wsGetMenu
    );

    @WebResult(name = "WSString", targetNamespace = "urn-com-amalto-xtentis-webservice", partName = "wsString")
    @WebMethod
    public WSString versioningGetItemContent(
        @WebParam(partName = "wsVersioningGetItemContent", name = "WSVersioningGetItemContent", targetNamespace = "urn-com-amalto-xtentis-webservice")
        WSVersioningGetItemContent wsVersioningGetItemContent
    );

    @WebResult(name = "WSRoutingRulePK", targetNamespace = "urn-com-amalto-xtentis-webservice", partName = "wsRoutingRulePK")
    @WebMethod
    public WSRoutingRulePK putRoutingRule(
        @WebParam(partName = "wsRoutingRule", name = "WSPutRoutingRule", targetNamespace = "urn-com-amalto-xtentis-webservice")
        WSPutRoutingRule wsRoutingRule
    );

    @WebResult(name = "WSBoolean", targetNamespace = "urn-com-amalto-xtentis-webservice", partName = "wsBoolean")
    @WebMethod
    public WSBoolean existsDataCluster(
        @WebParam(partName = "wsExistsDataCluster", name = "WSExistsDataCluster", targetNamespace = "urn-com-amalto-xtentis-webservice")
        WSExistsDataCluster wsExistsDataCluster
    );

    @WebResult(name = "WSItemPK", targetNamespace = "urn-com-amalto-xtentis-webservice", partName = "wsItemPK")
    @WebMethod
    public WSItemPK deleteItem(
        @WebParam(partName = "wsDeleteItem", name = "WSDeleteItem", targetNamespace = "urn-com-amalto-xtentis-webservice")
        WSDeleteItem wsDeleteItem
    );

    @WebResult(name = "WSItemPK", targetNamespace = "urn-com-amalto-xtentis-webservice", partName = "wsItemPK")
    @WebMethod
    public WSItemPK recoverDroppedItem(
        @WebParam(partName = "wsRecoverDroppedItem", name = "WSRecoverDroppedItem", targetNamespace = "urn-com-amalto-xtentis-webservice")
        WSRecoverDroppedItem wsRecoverDroppedItem
    );

    @WebResult(name = "WSBoolean", targetNamespace = "urn-com-amalto-xtentis-webservice", partName = "wsBoolean")
    @WebMethod
    public WSBoolean existsSynchronizationItem(
        @WebParam(partName = "wsExistsSynchronizationItem", name = "WSExistsSynchronizationItem", targetNamespace = "urn-com-amalto-xtentis-webservice")
        WSExistsSynchronizationItem wsExistsSynchronizationItem
    );

    @WebResult(name = "WSViewPK", targetNamespace = "urn-com-amalto-xtentis-webservice", partName = "wsViewPK")
    @WebMethod
    public WSViewPK putView(
        @WebParam(partName = "wsView", name = "WSPutView", targetNamespace = "urn-com-amalto-xtentis-webservice")
        WSPutView wsView
    );

    @WebResult(name = "WSConceptKey", targetNamespace = "urn-com-amalto-xtentis-webservice", partName = "wsconceptKey")
    @WebMethod
    public WSConceptKey getBusinessConceptKey(
        @WebParam(partName = "wsGetBusinessConceptKey", name = "WSGetBusinessConceptKey", targetNamespace = "urn-com-amalto-xtentis-webservice")
        WSGetBusinessConceptKey wsGetBusinessConceptKey
    );

    @WebResult(name = "WSBackgroundJobPK", targetNamespace = "urn-com-amalto-xtentis-webservice", partName = "wsBackgroundJobPK")
    @WebMethod
    public WSBackgroundJobPK processBytesUsingTransformerAsBackgroundJob(
        @WebParam(partName = "wsProcessBytesUsingTransformerAsBackgroundJob", name = "WSProcessBytesUsingTransformerAsBackgroundJob", targetNamespace = "urn-com-amalto-xtentis-webservice")
        WSProcessBytesUsingTransformerAsBackgroundJob wsProcessBytesUsingTransformerAsBackgroundJob
    );

    @WebResult(name = "WSBackgroundJobPK", targetNamespace = "urn-com-amalto-xtentis-webservice", partName = "wsBackgroundJobPK")
    @WebMethod
    public WSBackgroundJobPK versioningRestoreItems(
        @WebParam(partName = "wsVersioningRestoreItems", name = "WSVersioningRestoreItems", targetNamespace = "urn-com-amalto-xtentis-webservice")
        WSVersioningRestoreItems wsVersioningRestoreItems
    );

    @WebResult(name = "WSStringArray", targetNamespace = "urn-com-amalto-xtentis-webservice", partName = "results")
    @WebMethod
    public WSStringArray quickSearch(
        @WebParam(partName = "wsQuickSearch", name = "WSQuickSearch", targetNamespace = "urn-com-amalto-xtentis-webservice")
        WSQuickSearch wsQuickSearch
    );

    @WebResult(name = "WSBoolean", targetNamespace = "urn-com-amalto-xtentis-webservice", partName = "wsBoolean")
    @WebMethod
    public WSBoolean versioningRestoreItemByRevision(
        @WebParam(partName = "wsVersioningRestoreItemByRevision", name = "WSVersioningRestoreItemByRevision", targetNamespace = "urn-com-amalto-xtentis-webservice")
        WSVersioningRestoreItemByRevision wsVersioningRestoreItemByRevision
    );

    @WebResult(name = "WSDataModel", targetNamespace = "urn-com-amalto-xtentis-webservice", partName = "wsDataModel")
    @WebMethod
    public WSDataModel getDataModel(
        @WebParam(partName = "wsDataModelget", name = "WSGetDataModel", targetNamespace = "urn-com-amalto-xtentis-webservice")
        WSGetDataModel wsDataModelget
    );

    @WebResult(name = "WSMDMConfig", targetNamespace = "urn-com-amalto-xtentis-webservice", partName = "wsMDMConfig")
    @WebMethod
    public WSMDMConfig getMDMConfiguration();

    @WebResult(name = "WSDroppedItemPK", targetNamespace = "urn-com-amalto-xtentis-webservice", partName = "wsDroppedItemPK")
    @WebMethod
    public WSDroppedItemPK dropItem(
        @WebParam(partName = "wsDropItem", name = "WSDropItem", targetNamespace = "urn-com-amalto-xtentis-webservice")
        WSDropItem wsDropItem
    );

    @WebResult(name = "WSBoolean", targetNamespace = "urn-com-amalto-xtentis-webservice", partName = "wsBoolean")
    @WebMethod
    public WSBoolean existsUniverse(
        @WebParam(partName = "wsExistsUniverse", name = "WSExistsUniverse", targetNamespace = "urn-com-amalto-xtentis-webservice")
        WSExistsUniverse wsExistsUniverse
    );

    @WebResult(name = "WSStringArray", targetNamespace = "urn-com-amalto-xtentis-webservice", partName = "results")
    @WebMethod
    public WSStringArray viewSearch(
        @WebParam(partName = "wsViewSearch", name = "WSViewSearch", targetNamespace = "urn-com-amalto-xtentis-webservice")
        WSViewSearch wsViewSearch
    );

    @WebResult(name = "WSStringArray", targetNamespace = "urn-com-amalto-xtentis-webservice", partName = "results")
    @WebMethod
    public WSStringArray getItems(
        @WebParam(partName = "wsGetItems", name = "WSGetItems", targetNamespace = "urn-com-amalto-xtentis-webservice")
        WSGetItems wsGetItems
    );

    @WebResult(name = "WSRoutingOrderV2Array", targetNamespace = "urn-com-amalto-xtentis-webservice", partName = "wsRoutingOrderArray")
    @WebMethod(operationName = "getRoutingOrderV2sByCriteria")
    public WSRoutingOrderV2Array getRoutingOrderV2SByCriteria(
        @WebParam(partName = "wsGetRoutingOrderV2sByCriteria", name = "WSGetRoutingOrderV2sByCriteria", targetNamespace = "urn-com-amalto-xtentis-webservice")
        WSGetRoutingOrderV2SByCriteria wsGetRoutingOrderV2SByCriteria
    );

    @WebResult(name = "WSUniversePKArray", targetNamespace = "urn-com-amalto-xtentis-webservice", partName = "wsUniversePKArray")
    @WebMethod
    public WSUniversePKArray getUniverseByRevision(
        @WebParam(partName = "wsUniverseByRevision", name = "WSGetUniverseByRevision", targetNamespace = "urn-com-amalto-xtentis-webservice")
        WSGetUniverseByRevision wsUniverseByRevision
    );

    @WebResult(name = "WSRoutingRulePK", targetNamespace = "urn-com-amalto-xtentis-webservice", partName = "wsRoutingRulePK")
    @WebMethod
    public WSRoutingRulePK deleteRoutingRule(
        @WebParam(partName = "wsRoutingRuleDel", name = "WSDeleteRoutingRule", targetNamespace = "urn-com-amalto-xtentis-webservice")
        WSDeleteRoutingRule wsRoutingRuleDel
    );

    @WebResult(name = "WSStringArray", targetNamespace = "urn-com-amalto-xtentis-webservice", partName = "results")
    @WebMethod
    public WSStringArray getItemsPivotIndex(
        @WebParam(partName = "wsGetItemsPivotIndex", name = "WSGetItemsPivotIndex", targetNamespace = "urn-com-amalto-xtentis-webservice")
        WSGetItemsPivotIndex wsGetItemsPivotIndex
    );

    @WebResult(name = "WSUniverse", targetNamespace = "urn-com-amalto-xtentis-webservice", partName = "wsUniverse")
    @WebMethod
    public WSUniverse getCurrentUniverse(
        @WebParam(partName = "wsGetCurrentUniverse", name = "WSGetCurrentUniverse", targetNamespace = "urn-com-amalto-xtentis-webservice")
        WSGetCurrentUniverse wsGetCurrentUniverse
    );

    @WebResult(name = "WSSynchronizationPlanPK", targetNamespace = "urn-com-amalto-xtentis-webservice", partName = "wsSynchronizationPlanPK")
    @WebMethod
    public WSSynchronizationPlanPK deleteSynchronizationPlan(
        @WebParam(partName = "wsSynchronizationPlanDelete", name = "WSDeleteSynchronizationPlan", targetNamespace = "urn-com-amalto-xtentis-webservice")
        WSDeleteSynchronizationPlan wsSynchronizationPlanDelete
    );

    @WebResult(name = "WSRolePKArray", targetNamespace = "urn-com-amalto-xtentis-webservice", partName = "wsRolePKArray")
    @WebMethod
    public WSRolePKArray getRolePKs(
        @WebParam(partName = "regex", name = "WSGetRolePKs", targetNamespace = "urn-com-amalto-xtentis-webservice")
        WSGetRolePKs regex
    );

    @WebResult(name = "WSItemPKArray", targetNamespace = "urn-com-amalto-xtentis-webservice", partName = "wsItemPKArray")
    @WebMethod
    public WSItemPKArray putItemArray(
        @WebParam(partName = "wsPutItemArray", name = "WSPutItemArray", targetNamespace = "urn-com-amalto-xtentis-webservice")
        WSPutItemArray wsPutItemArray
    );

    @WebResult(name = "WSBackgroundJobPK", targetNamespace = "urn-com-amalto-xtentis-webservice", partName = "wsBackgroundJobPK")
    @WebMethod
    public WSBackgroundJobPK executeTransformerV2AsJob(
        @WebParam(partName = "wsExecuteTransformerV2AsJob", name = "WSExecuteTransformerV2AsJob", targetNamespace = "urn-com-amalto-xtentis-webservice")
        WSExecuteTransformerV2AsJob wsExecuteTransformerV2AsJob
    );

    @WebResult(name = "WSBoolean", targetNamespace = "urn-com-amalto-xtentis-webservice", partName = "wsBoolean")
    @WebMethod
    public WSBoolean existsTransformer(
        @WebParam(partName = "wsExistsTransformer", name = "WSExistsTransformer", targetNamespace = "urn-com-amalto-xtentis-webservice")
        WSExistsTransformer wsExistsTransformer
    );

    @WebResult(name = "WSServicesList", targetNamespace = "urn-com-amalto-xtentis-webservice", partName = "wsServicesList")
    @WebMethod
    public WSServicesList getServicesList(
        @WebParam(partName = "wsGetServicesList", name = "WSGetServicesList", targetNamespace = "urn-com-amalto-xtentis-webservice")
        WSGetServicesList wsGetServicesList
    );

    @WebResult(name = "WSUniversePK", targetNamespace = "urn-com-amalto-xtentis-webservice", partName = "wsUniversePK")
    @WebMethod
    public WSUniversePK putUniverse(
        @WebParam(partName = "wsUniverse", name = "WSPutUniverse", targetNamespace = "urn-com-amalto-xtentis-webservice")
        WSPutUniverse wsUniverse
    );

    @WebResult(name = "WSVersioningInfo", targetNamespace = "urn-com-amalto-xtentis-webservice", partName = "wsVersioningInfo")
    @WebMethod
    public WSVersioningInfo versioningGetInfo(
        @WebParam(partName = "wsVersioningGetInfo", name = "WSVersioningGetInfo", targetNamespace = "urn-com-amalto-xtentis-webservice")
        WSVersioningGetInfo wsVersioningGetInfo
    );

    @WebResult(name = "WSBackgroundJob", targetNamespace = "urn-com-amalto-xtentis-webservice", partName = "wsBackgroundJob")
    @WebMethod
    public WSBackgroundJob getBackgroundJob(
        @WebParam(partName = "wsGetBackgroundJob", name = "WSGetBackgroundJob", targetNamespace = "urn-com-amalto-xtentis-webservice")
        WSGetBackgroundJob wsGetBackgroundJob
    );

    @WebResult(name = "WSString", targetNamespace = "urn-com-amalto-xtentis-webservice", partName = "dummy")
    @WebMethod
    public WSString logout(
        @WebParam(partName = "wsLogout", name = "WSLogout", targetNamespace = "urn-com-amalto-xtentis-webservice")
        WSLogout wsLogout
    );

    @WebResult(name = "WSItem", targetNamespace = "urn-com-amalto-xtentis-webservice", partName = "wsItem")
    @WebMethod
    public WSItem getItem(
        @WebParam(partName = "wsGetItem", name = "WSGetItem", targetNamespace = "urn-com-amalto-xtentis-webservice")
        WSGetItem wsGetItem
    );

    @WebResult(name = "WSRoutingOrderV2PKArray", targetNamespace = "urn-com-amalto-xtentis-webservice", partName = "wsRoutingOrderPKArray")
    @WebMethod
    public WSRoutingOrderV2PKArray getRoutingOrderV2PKsByCriteria(
        @WebParam(partName = "wsGetRoutingOrderV2PKsByCriteria", name = "WSGetRoutingOrderV2PKsByCriteria", targetNamespace = "urn-com-amalto-xtentis-webservice")
        WSGetRoutingOrderV2PKsByCriteria wsGetRoutingOrderV2PKsByCriteria
    );

    @WebResult(name = "WSBoolean", targetNamespace = "urn-com-amalto-xtentis-webservice", partName = "wsBoolean")
    @WebMethod
    public WSBoolean existsRole(
        @WebParam(partName = "wsExistsRole", name = "WSExistsRole", targetNamespace = "urn-com-amalto-xtentis-webservice")
        WSExistsRole wsExistsRole
    );

    @WebResult(name = "WSTransformerPKArray", targetNamespace = "urn-com-amalto-xtentis-webservice", partName = "wsTransformerPKArray")
    @WebMethod
    public WSTransformerPKArray getTransformerPKs(
        @WebParam(partName = "regex", name = "WSGetTransformerPKs", targetNamespace = "urn-com-amalto-xtentis-webservice")
        WSGetTransformerPKs regex
    );

    @WebResult(name = "WSRolePK", targetNamespace = "urn-com-amalto-xtentis-webservice", partName = "wsRolePK")
    @WebMethod
    public WSRolePK putRole(
        @WebParam(partName = "wsRole", name = "WSPutRole", targetNamespace = "urn-com-amalto-xtentis-webservice")
        WSPutRole wsRole
    );

    @WebResult(name = "WSItemPK", targetNamespace = "urn-com-amalto-xtentis-webservice", partName = "wsItemPK")
    @WebMethod
    public WSItemPK putItemWithReport(
        @WebParam(partName = "wsPutItemWithReport", name = "WSPutItemWithReport", targetNamespace = "urn-com-amalto-xtentis-webservice")
        WSPutItemWithReport wsPutItemWithReport
    );

    @WebResult(name = "WSDroppedItem", targetNamespace = "urn-com-amalto-xtentis-webservice", partName = "wsDroppedItem")
    @WebMethod
    public WSDroppedItem loadDroppedItem(
        @WebParam(partName = "wsLoadDroppedItem", name = "WSLoadDroppedItem", targetNamespace = "urn-com-amalto-xtentis-webservice")
        WSLoadDroppedItem wsLoadDroppedItem
    );

    @WebResult(name = "WSItemPK", targetNamespace = "urn-com-amalto-xtentis-webservice", partName = "wsItemPK")
    @WebMethod
    public WSItemPK synchronizationPutItemXML(
        @WebParam(partName = "wsSynchronizationPutItemXML", name = "WSSynchronizationPutItemXML", targetNamespace = "urn-com-amalto-xtentis-webservice")
        WSSynchronizationPutItemXML wsSynchronizationPutItemXML
    );

    @WebResult(name = "WSStringArray", targetNamespace = "urn-com-amalto-xtentis-webservice", partName = "values")
    @WebMethod
    public WSStringArray getFullPathValues(
        @WebParam(partName = "wsGetFullPathValues", name = "WSGetFullPathValues", targetNamespace = "urn-com-amalto-xtentis-webservice")
        WSGetFullPathValues wsGetFullPathValues
    );

    @WebResult(name = "WSBoolean", targetNamespace = "urn-com-amalto-xtentis-webservice", partName = "wsBoolean")
    @WebMethod
    public WSBoolean existsMenu(
        @WebParam(partName = "wsExistsMenu", name = "WSExistsMenu", targetNamespace = "urn-com-amalto-xtentis-webservice")
        WSExistsMenu wsExistsMenu
    );

    @WebResult(name = "WSItemPKArray", targetNamespace = "urn-com-amalto-xtentis-webservice", partName = "wsItemPKArray")
    @WebMethod
    public WSItemPKArray putItemWithReportArray(
        @WebParam(partName = "wsPutItemWithReportArray", name = "WSPutItemWithReportArray", targetNamespace = "urn-com-amalto-xtentis-webservice")
        WSPutItemWithReportArray wsPutItemWithReportArray
    );

    @WebResult(name = "WSVersion", targetNamespace = "urn-com-amalto-xtentis-webservice", partName = "wsVersion")
    @WebMethod
    public WSVersion getComponentVersion(
        @WebParam(partName = "wsGetComponentVersion", name = "WSGetComponentVersion", targetNamespace = "urn-com-amalto-xtentis-webservice")
        WSGetComponentVersion wsGetComponentVersion
    );

    @WebResult(name = "WSSynchronizationItemPK", targetNamespace = "urn-com-amalto-xtentis-webservice", partName = "wsSynchronizationItemPK")
    @WebMethod
    public WSSynchronizationItemPK deleteSynchronizationItem(
        @WebParam(partName = "wsSynchronizationItemDelete", name = "WSDeleteSynchronizationItem", targetNamespace = "urn-com-amalto-xtentis-webservice")
        WSDeleteSynchronizationItem wsSynchronizationItemDelete
    );

    @WebResult(name = "WSRoutingRule", targetNamespace = "urn-com-amalto-xtentis-webservice", partName = "wsRoutingRule")
    @WebMethod
    public WSRoutingRule getRoutingRule(
        @WebParam(partName = "wsRoutingRulePK", name = "WSGetRoutingRule", targetNamespace = "urn-com-amalto-xtentis-webservice")
        WSGetRoutingRule wsRoutingRulePK
    );

    @WebResult(name = "WSTransformerPluginV2sList", targetNamespace = "urn-com-amalto-xtentis-webservice", partName = "wsTransformerPluginV2sList")
    @WebMethod(operationName = "getTransformerPluginV2sList")
    public WSTransformerPluginV2SList getTransformerPluginV2SList(
        @WebParam(partName = "wsGetTransformerPluginV2sList", name = "WSGetTransformerPluginV2sList", targetNamespace = "urn-com-amalto-xtentis-webservice")
        WSGetTransformerPluginV2SList wsGetTransformerPluginV2SList
    );

    @WebResult(name = "WSViewPK", targetNamespace = "urn-com-amalto-xtentis-webservice", partName = "wsViewPK")
    @WebMethod
    public WSViewPK deleteView(
        @WebParam(partName = "wsViewDel", name = "WSDeleteView", targetNamespace = "urn-com-amalto-xtentis-webservice")
        WSDeleteView wsViewDel
    );

    @WebResult(name = "WSStoredProcedure", targetNamespace = "urn-com-amalto-xtentis-webservice", partName = "wsStoredProcedure")
    @WebMethod
    public WSStoredProcedure getStoredProcedure(
        @WebParam(partName = "wsGetStoredProcedure", name = "WSGetStoredProcedure", targetNamespace = "urn-com-amalto-xtentis-webservice")
        WSGetStoredProcedure wsGetStoredProcedure
    );

    @WebResult(name = "WSBoolean", targetNamespace = "urn-com-amalto-xtentis-webservice", partName = "wsBoolean")
    @WebMethod
    public WSBoolean existsDBDataCluster(
        @WebParam(partName = "wsExistsDBDataCluster", name = "WSExistsDBDataCluster", targetNamespace = "urn-com-amalto-xtentis-webservice")
        WSExistsDBDataCluster wsExistsDBDataCluster
    );

    @WebResult(name = "WSUniversePK", targetNamespace = "urn-com-amalto-xtentis-webservice", partName = "wsUniversePK")
    @WebMethod
    public WSUniversePK deleteUniverse(
        @WebParam(partName = "wsUniverseDelete", name = "WSDeleteUniverse", targetNamespace = "urn-com-amalto-xtentis-webservice")
        WSDeleteUniverse wsUniverseDelete
    );

    @WebResult(name = "WSSynchronizationPlan", targetNamespace = "urn-com-amalto-xtentis-webservice", partName = "wsSynchronizationPlan")
    @WebMethod
    public WSSynchronizationPlan getSynchronizationPlan(
        @WebParam(partName = "wsGetSynchronizationPlan", name = "WSGetSynchronizationPlan", targetNamespace = "urn-com-amalto-xtentis-webservice")
        WSGetSynchronizationPlan wsGetSynchronizationPlan
    );

    @WebResult(name = "WSString", targetNamespace = "urn-com-amalto-xtentis-webservice", partName = "configuration")
    @WebMethod
    public WSString getTransformerPluginV2Configuration(
        @WebParam(partName = "wsGetConfiguration", name = "WSTransformerPluginV2GetConfiguration", targetNamespace = "urn-com-amalto-xtentis-webservice")
        WSTransformerPluginV2GetConfiguration wsGetConfiguration
    );

    @WebResult(name = "WSUniverse", targetNamespace = "urn-com-amalto-xtentis-webservice", partName = "wsUniverse")
    @WebMethod
    public WSUniverse getUniverse(
        @WebParam(partName = "wsGetUniverse", name = "WSGetUniverse", targetNamespace = "urn-com-amalto-xtentis-webservice")
        WSGetUniverse wsGetUniverse
    );

    @WebResult(name = "WSRoutingOrderV2", targetNamespace = "urn-com-amalto-xtentis-webservice", partName = "wsRoutingOrder")
    @WebMethod
    public WSRoutingOrderV2 existsRoutingOrderV2(
        @WebParam(partName = "wsExistsRoutingOrder", name = "WSExistsRoutingOrderV2", targetNamespace = "urn-com-amalto-xtentis-webservice")
        WSExistsRoutingOrderV2 wsExistsRoutingOrder
    );

    @WebResult(name = "WSRoutingOrderV2", targetNamespace = "urn-com-amalto-xtentis-webservice", partName = "wsRoutingOrder")
    @WebMethod
    public WSRoutingOrderV2 getRoutingOrderV2(
        @WebParam(partName = "wsGetRoutingOrderV2", name = "WSGetRoutingOrderV2", targetNamespace = "urn-com-amalto-xtentis-webservice")
        WSGetRoutingOrderV2 wsGetRoutingOrderV2
    );

    @WebResult(name = "WSSynchronizationItemPKArray", targetNamespace = "urn-com-amalto-xtentis-webservice", partName = "wsSynchronizationItemPKArray")
    @WebMethod
    public WSSynchronizationItemPKArray getSynchronizationItemPKs(
        @WebParam(partName = "regex", name = "WSGetSynchronizationItemPKs", targetNamespace = "urn-com-amalto-xtentis-webservice")
        WSGetSynchronizationItemPKs regex
    );

    @WebResult(name = "WSBoolean", targetNamespace = "urn-com-amalto-xtentis-webservice", partName = "wsBoolean")
    @WebMethod
    public WSBoolean existsDataModel(
        @WebParam(partName = "wsDataModelExists", name = "WSExistsDataModel", targetNamespace = "urn-com-amalto-xtentis-webservice")
        WSExistsDataModel wsDataModelExists
    );

    @WebResult(name = "WSBackgroundJobPK", targetNamespace = "urn-com-amalto-xtentis-webservice", partName = "wsBackgroundJobPK")
    @WebMethod
    public WSBackgroundJobPK versioningTagObjects(
        @WebParam(partName = "wsVersioningTagObjects", name = "WSVersioningTagObjects", targetNamespace = "urn-com-amalto-xtentis-webservice")
        WSVersioningTagObjects wsVersioningTagObjects
    );

    @WebResult(name = "WSString", targetNamespace = "urn-com-amalto-xtentis-webservice", partName = "result")
    @WebMethod
    public WSString executeRoutingOrderV2Synchronously(
        @WebParam(partName = "wsExecuteRoutingOrderSynchronously", name = "WSExecuteRoutingOrderV2Synchronously", targetNamespace = "urn-com-amalto-xtentis-webservice")
        WSExecuteRoutingOrderV2Synchronously wsExecuteRoutingOrderSynchronously
    );

    @WebResult(name = "WSBackgroundJobPK", targetNamespace = "urn-com-amalto-xtentis-webservice", partName = "wsBackgroundJobPK")
    @WebMethod
    public WSBackgroundJobPK versioningTagUniverse(
        @WebParam(partName = "wsVersioningTagUniverse", name = "WSVersioningTagUniverse", targetNamespace = "urn-com-amalto-xtentis-webservice")
        WSVersioningTagUniverse wsVersioningTagUniverse
    );

    @WebResult(name = "WSTransformerV2", targetNamespace = "urn-com-amalto-xtentis-webservice", partName = "wsTransformerV2")
    @WebMethod
    public WSTransformerV2 getTransformerV2(
        @WebParam(partName = "wsGetTransformerV2", name = "WSGetTransformerV2", targetNamespace = "urn-com-amalto-xtentis-webservice")
        WSGetTransformerV2 wsGetTransformerV2
    );

    @WebResult(name = "WSInt", targetNamespace = "urn-com-amalto-xtentis-webservice", partName = "numItems")
    @WebMethod
    public WSInt deleteItems(
        @WebParam(partName = "wsDeleteItems", name = "WSDeleteItems", targetNamespace = "urn-com-amalto-xtentis-webservice")
        WSDeleteItems wsDeleteItems
    );

    @WebResult(name = "WSTransformerContext", targetNamespace = "urn-com-amalto-xtentis-webservice", partName = "wsTransformerContext")
    @WebMethod
    public WSTransformerContext extractThroughTransformerV2(
        @WebParam(partName = "wsExtractThroughTransformerV2", name = "WSExtractThroughTransformerV2", targetNamespace = "urn-com-amalto-xtentis-webservice")
        WSExtractThroughTransformerV2 wsExtractThroughTransformerV2
    );

    @WebResult(name = "WSServiceGetDocument", targetNamespace = "urn-com-amalto-xtentis-webservice", partName = "result")
    @WebMethod
    public WSServiceGetDocument getServiceDocument(
        @WebParam(partName = "serviceName", name = "WSString", targetNamespace = "urn-com-amalto-xtentis-webservice")
        WSString serviceName
    );

    @WebResult(name = "WSVersioningItemsVersions", targetNamespace = "urn-com-amalto-xtentis-webservice", partName = "wsVersioningItemsVersions")
    @WebMethod
    public WSVersioningItemsVersions versioningGetItemsVersions(
        @WebParam(partName = "wsVersioningGetItemsVersions", name = "WSVersioningGetItemsVersions", targetNamespace = "urn-com-amalto-xtentis-webservice")
        WSVersioningGetItemsVersions wsVersioningGetItemsVersions
    );

    @WebResult(name = "WSTransformerPK", targetNamespace = "urn-com-amalto-xtentis-webservice", partName = "wsTransformerPK")
    @WebMethod
    public WSTransformerPK putTransformer(
        @WebParam(partName = "wsTransformer", name = "WSPutTransformer", targetNamespace = "urn-com-amalto-xtentis-webservice")
        WSPutTransformer wsTransformer
    );

    @WebResult(name = "WSStringArray", targetNamespace = "urn-com-amalto-xtentis-webservice", partName = "wsSynchronizationPlanAlgorithmNames")
    @WebMethod
    public WSStringArray getSynchronizationPlanObjectsAlgorithms(
        @WebParam(partName = "regex", name = "WSGetSynchronizationPlanObjectsAlgorithms", targetNamespace = "urn-com-amalto-xtentis-webservice")
        WSGetSynchronizationPlanObjectsAlgorithms regex
    );

    @WebResult(name = "WSSynchronizationPlanPKArray", targetNamespace = "urn-com-amalto-xtentis-webservice", partName = "wsSynchronizationPlanPKArray")
    @WebMethod
    public WSSynchronizationPlanPKArray getSynchronizationPlanPKs(
        @WebParam(partName = "regex", name = "WSGetSynchronizationPlanPKs", targetNamespace = "urn-com-amalto-xtentis-webservice")
        WSGetSynchronizationPlanPKs regex
    );

    @WebResult(name = "WSStringArray", targetNamespace = "urn-com-amalto-xtentis-webservice", partName = "results")
    @WebMethod
    public WSStringArray xPathsSearch(
        @WebParam(partName = "wsXPathsSearch", name = "WSXPathsSearch", targetNamespace = "urn-com-amalto-xtentis-webservice")
        WSXPathsSearch wsXPathsSearch
    );

    @WebResult(name = "WSString", targetNamespace = "urn-com-amalto-xtentis-webservice", partName = "result")
    @WebMethod
    public WSString putTransformerPluginV2Configuration(
        @WebParam(partName = "wsPutConfiguration", name = "WSTransformerPluginV2PutConfiguration", targetNamespace = "urn-com-amalto-xtentis-webservice")
        WSTransformerPluginV2PutConfiguration wsPutConfiguration
    );

    @WebResult(name = "WSBoolean", targetNamespace = "urn-com-amalto-xtentis-webservice", partName = "wsBoolean")
    @WebMethod
    public WSBoolean existsItem(
        @WebParam(partName = "wsExistsItem", name = "WSExistsItem", targetNamespace = "urn-com-amalto-xtentis-webservice")
        WSExistsItem wsExistsItem
    );

    @WebResult(name = "WSDataModelPK", targetNamespace = "urn-com-amalto-xtentis-webservice", partName = "wsDataModelPK")
    @WebMethod
    public WSDataModelPK deleteDataModel(
        @WebParam(partName = "wsDeleteDataModel", name = "WSDeleteDataModel", targetNamespace = "urn-com-amalto-xtentis-webservice")
        WSDeleteDataModel wsDeleteDataModel
    );

    @WebResult(name = "WSBackgroundJobPK", targetNamespace = "urn-com-amalto-xtentis-webservice", partName = "wsBackgroundJobPK")
    @WebMethod
    public WSBackgroundJobPK versioningRestoreObjects(
        @WebParam(partName = "wsVersioningRestoreObjects", name = "WSVersioningRestoreObjects", targetNamespace = "urn-com-amalto-xtentis-webservice")
        WSVersioningRestoreObjects wsVersioningRestoreObjects
    );

    @WebResult(name = "WSSynchronizationItem", targetNamespace = "urn-com-amalto-xtentis-webservice", partName = "wsSynchronizationItem")
    @WebMethod
    public WSSynchronizationItem getSynchronizationItem(
        @WebParam(partName = "wsGetSynchronizationItem", name = "WSGetSynchronizationItem", targetNamespace = "urn-com-amalto-xtentis-webservice")
        WSGetSynchronizationItem wsGetSynchronizationItem
    );

    @WebResult(name = "WSConceptRevisionMap", targetNamespace = "urn-com-amalto-xtentis-webservice", partName = "wsConceptRevisionMap")
    @WebMethod
    public WSConceptRevisionMap getConceptsInDataClusterWithRevisions(
        @WebParam(partName = "wsGetConceptsInDataClusterWithRevisions", name = "WSGetConceptsInDataClusterWithRevisions", targetNamespace = "urn-com-amalto-xtentis-webservice")
        WSGetConceptsInDataClusterWithRevisions wsGetConceptsInDataClusterWithRevisions
    );

    @WebResult(name = "WSBoolean", targetNamespace = "urn-com-amalto-xtentis-webservice", partName = "wsBoolean")
    @WebMethod
    public WSBoolean existsSynchronizationPlan(
        @WebParam(partName = "wsExistsSynchronizationPlan", name = "WSExistsSynchronizationPlan", targetNamespace = "urn-com-amalto-xtentis-webservice")
        WSExistsSynchronizationPlan wsExistsSynchronizationPlan
    );

    @WebResult(name = "WSItemPKArray", targetNamespace = "urn-com-amalto-xtentis-webservice", partName = "wsItemPKArray")
    @WebMethod
    public WSItemPKArray synchronizationGetUnsynchronizedItemPKs(
        @WebParam(partName = "wsSynchronizationGetUnsynchronizedItemPKs", name = "WSSynchronizationGetUnsynchronizedItemPKs", targetNamespace = "urn-com-amalto-xtentis-webservice")
        WSSynchronizationGetUnsynchronizedItemPKs wsSynchronizationGetUnsynchronizedItemPKs
    );

    @WebResult(name = "WSRolePK", targetNamespace = "urn-com-amalto-xtentis-webservice", partName = "wsRolePK")
    @WebMethod
    public WSRolePK deleteRole(
        @WebParam(partName = "wsRoleDelete", name = "WSDeleteRole", targetNamespace = "urn-com-amalto-xtentis-webservice")
        WSDeleteRole wsRoleDelete
    );

    @WebResult(name = "WSStringArray", targetNamespace = "urn-com-amalto-xtentis-webservice", partName = "wsRoleNames")
    @WebMethod
    public WSStringArray getObjectsForRoles(
        @WebParam(partName = "wsRoleDelete", name = "WSGetObjectsForRoles", targetNamespace = "urn-com-amalto-xtentis-webservice")
        WSGetObjectsForRoles wsRoleDelete
    );

    @WebResult(name = "WSStringArray", targetNamespace = "urn-com-amalto-xtentis-webservice", partName = "results")
    @WebMethod
    public WSStringArray executeStoredProcedure(
        @WebParam(partName = "wsExecuteStoredProcedure", name = "WSExecuteStoredProcedure", targetNamespace = "urn-com-amalto-xtentis-webservice")
        WSExecuteStoredProcedure wsExecuteStoredProcedure
    );

    @WebResult(name = "WSStoredProcedurePK", targetNamespace = "urn-com-amalto-xtentis-webservice", partName = "wsStoredProcedurePK")
    @WebMethod
    public WSStoredProcedurePK putStoredProcedure(
        @WebParam(partName = "wsStoredProcedure", name = "WSPutStoredProcedure", targetNamespace = "urn-com-amalto-xtentis-webservice")
        WSPutStoredProcedure wsStoredProcedure
    );

    @WebResult(name = "WSString", targetNamespace = "urn-com-amalto-xtentis-webservice", partName = "wsBusinessConceptName")
    @WebMethod
    public WSString putBusinessConceptSchema(
        @WebParam(partName = "wsPutBusinessConceptSchema", name = "WSPutBusinessConceptSchema", targetNamespace = "urn-com-amalto-xtentis-webservice")
        WSPutBusinessConceptSchema wsPutBusinessConceptSchema
    );

    @WebResult(name = "WSViewPKArray", targetNamespace = "urn-com-amalto-xtentis-webservice", partName = "wsViewPKs")
    @WebMethod
    public WSViewPKArray getViewPKs(
        @WebParam(partName = "regexp", name = "WSGetViewPKs", targetNamespace = "urn-com-amalto-xtentis-webservice")
        WSGetViewPKs regexp
    );

    @WebResult(name = "WSStringArray", targetNamespace = "urn-com-amalto-xtentis-webservice", partName = "wsConcepts")
    @WebMethod
    public WSStringArray getConceptsInDataCluster(
        @WebParam(partName = "wsGetConceptsInDataCluster", name = "WSGetConceptsInDataCluster", targetNamespace = "urn-com-amalto-xtentis-webservice")
        WSGetConceptsInDataCluster wsGetConceptsInDataCluster
    );

    @WebResult(name = "WSString", targetNamespace = "urn-com-amalto-xtentis-webservice", partName = "statusString")
    @WebMethod
    public WSString serviceAction(
        @WebParam(partName = "wsServiceAction", name = "WSServiceAction", targetNamespace = "urn-com-amalto-xtentis-webservice")
        WSServiceAction wsServiceAction
    );

    @WebResult(name = "WSView", targetNamespace = "urn-com-amalto-xtentis-webservice", partName = "wsView")
    @WebMethod
    public WSView getView(
        @WebParam(partName = "wsViewPK", name = "WSGetView", targetNamespace = "urn-com-amalto-xtentis-webservice")
        WSGetView wsViewPK
    );

    @WebResult(name = "WSBoolean", targetNamespace = "urn-com-amalto-xtentis-webservice", partName = "wsBoolean")
    @WebMethod
    public WSBoolean existsStoredProcedure(
        @WebParam(partName = "wsExistsStoredProcedure", name = "WSExistsStoredProcedure", targetNamespace = "urn-com-amalto-xtentis-webservice")
        WSExistsStoredProcedure wsExistsStoredProcedure
    );

    @WebResult(name = "WSStringArray", targetNamespace = "urn-com-amalto-xtentis-webservice", partName = "wsBusinessConceptsNames")
    @WebMethod
    public WSStringArray getBusinessConcepts(
        @WebParam(partName = "wsGetBusinessConcepts", name = "WSGetBusinessConcepts", targetNamespace = "urn-com-amalto-xtentis-webservice")
        WSGetBusinessConcepts wsGetBusinessConcepts
    );

    @WebResult(name = "WSInt", targetNamespace = "urn-com-amalto-xtentis-webservice", partName = "bytes")
    @WebMethod
    public WSInt initMDM(
        @WebParam(partName = "initData", name = "WSInitData", targetNamespace = "urn-com-amalto-xtentis-webservice")
        WSInitData initData
    );

    @WebResult(name = "WSTransformerV2PKArray", targetNamespace = "urn-com-amalto-xtentis-webservice", partName = "wsTransformerV2PKArray")
    @WebMethod
    public WSTransformerV2PKArray getTransformerV2PKs(
        @WebParam(partName = "regex", name = "WSGetTransformerV2PKs", targetNamespace = "urn-com-amalto-xtentis-webservice")
        WSGetTransformerV2PKs regex
    );

    @WebResult(name = "WSTransformerPluginV2Details", targetNamespace = "urn-com-amalto-xtentis-webservice", partName = "result")
    @WebMethod
    public WSTransformerPluginV2Details getTransformerPluginV2Details(
        @WebParam(partName = "wsGetTransformerPluginV2Details", name = "WSGetTransformerPluginV2Details", targetNamespace = "urn-com-amalto-xtentis-webservice")
        WSGetTransformerPluginV2Details wsGetTransformerPluginV2Details
    );

    @WebResult(name = "WSDataModelPKArray", targetNamespace = "urn-com-amalto-xtentis-webservice", partName = "wsDataModelPKs")
    @WebMethod
    public WSDataModelPKArray getDataModelPKs(
        @WebParam(partName = "regexp", name = "WSRegexDataModelPKs", targetNamespace = "urn-com-amalto-xtentis-webservice")
        WSRegexDataModelPKs regexp
    );

    @WebResult(name = "WSBoolean", targetNamespace = "urn-com-amalto-xtentis-webservice", partName = "wsBoolean")
    @WebMethod
    public WSBoolean putDBDataCluster(
        @WebParam(partName = "wsDataCluster", name = "WSPutDBDataCluster", targetNamespace = "urn-com-amalto-xtentis-webservice")
        WSPutDBDataCluster wsDataCluster
    );

    @WebResult(name = "WSBackgroundJobPK", targetNamespace = "urn-com-amalto-xtentis-webservice", partName = "wsBackgroundJobPK")
    @WebMethod
    public WSBackgroundJobPK versioningRestoreUniverse(
        @WebParam(partName = "wsVersioningRestoreUniverse", name = "WSVersioningRestoreUniverse", targetNamespace = "urn-com-amalto-xtentis-webservice")
        WSVersioningRestoreUniverse wsVersioningRestoreUniverse
    );

    @WebResult(name = "WSDroppedItemPK", targetNamespace = "urn-com-amalto-xtentis-webservice", partName = "wsDroppedItemPK")
    @WebMethod
    public WSDroppedItemPK removeDroppedItem(
        @WebParam(partName = "wsRemoveDroppedItem", name = "WSRemoveDroppedItem", targetNamespace = "urn-com-amalto-xtentis-webservice")
        WSRemoveDroppedItem wsRemoveDroppedItem
    );

    @WebResult(name = "WSTransformerContext", targetNamespace = "urn-com-amalto-xtentis-webservice", partName = "wsTransformerContext")
    @WebMethod
    public WSTransformerContext executeTransformerV2(
        @WebParam(partName = "wsExecuteTransformerV2", name = "WSExecuteTransformerV2", targetNamespace = "urn-com-amalto-xtentis-webservice")
        WSExecuteTransformerV2 wsExecuteTransformerV2
    );

    @WebResult(name = "WSVersioningUniverseVersions", targetNamespace = "urn-com-amalto-xtentis-webservice", partName = "wsVersioningUniverseVersions")
    @WebMethod
    public WSVersioningUniverseVersions versioningGetUniverseVersions(
        @WebParam(partName = "wsVersioningGetUniverseVersions", name = "WSVersioningGetUniverseVersions", targetNamespace = "urn-com-amalto-xtentis-webservice")
        WSVersioningGetUniverseVersions wsVersioningGetUniverseVersions
    );

    @WebResult(name = "WSPipeline", targetNamespace = "urn-com-amalto-xtentis-webservice", partName = "wsPipeline")
    @WebMethod
    public WSPipeline processFileUsingTransformer(
        @WebParam(partName = "wsProcessFileUsingTransformer", name = "WSProcessFileUsingTransformer", targetNamespace = "urn-com-amalto-xtentis-webservice")
        WSProcessFileUsingTransformer wsProcessFileUsingTransformer
    );

    @WebResult(name = "WSMenuPK", targetNamespace = "urn-com-amalto-xtentis-webservice", partName = "wsMenuPK")
    @WebMethod
    public WSMenuPK putMenu(
        @WebParam(partName = "wsMenu", name = "WSPutMenu", targetNamespace = "urn-com-amalto-xtentis-webservice")
        WSPutMenu wsMenu
    );

    @WebResult(name = "WSString", targetNamespace = "urn-com-amalto-xtentis-webservice", partName = "configuration")
    @WebMethod
    public WSString getServiceConfiguration(
        @WebParam(partName = "wsGetConfiguration", name = "WSServiceGetConfiguration", targetNamespace = "urn-com-amalto-xtentis-webservice")
        WSServiceGetConfiguration wsGetConfiguration
    );

    @WebResult(name = "WSString", targetNamespace = "urn-com-amalto-xtentis-webservice", partName = "dummy")
    @WebMethod
    public WSString ping(
        @WebParam(partName = "wsPing", name = "WSPing", targetNamespace = "urn-com-amalto-xtentis-webservice")
        WSPing wsPing
    );

    @WebResult(name = "WSStringArray", targetNamespace = "urn-com-amalto-xtentis-webservice", partName = "wsStringArray")
    @WebMethod
    public WSStringArray synchronizationGetUnsynchronizedObjectsIDs(
        @WebParam(partName = "wsSynchronizationGetUnsynchronizedObjectsIDs", name = "WSSynchronizationGetUnsynchronizedObjectsIDs", targetNamespace = "urn-com-amalto-xtentis-webservice")
        WSSynchronizationGetUnsynchronizedObjectsIDs wsSynchronizationGetUnsynchronizedObjectsIDs
    );

    @WebResult(name = "WSBackgroundJobPK", targetNamespace = "urn-com-amalto-xtentis-webservice", partName = "wsBackgroundJobPK")
    @WebMethod
    public WSBackgroundJobPK processFileUsingTransformerAsBackgroundJob(
        @WebParam(partName = "wsProcessFileUsingTransformerAsBackgroundJob", name = "WSProcessFileUsingTransformerAsBackgroundJob", targetNamespace = "urn-com-amalto-xtentis-webservice")
        WSProcessFileUsingTransformerAsBackgroundJob wsProcessFileUsingTransformerAsBackgroundJob
    );

    @WebResult(name = "WSVersioningSystemConfiguration", targetNamespace = "urn-com-amalto-xtentis-webservice", partName = "wsVersioningSystemConfiguration")
    @WebMethod
    public WSVersioningSystemConfiguration getVersioningSystemConfiguration(
        @WebParam(partName = "wsGetVersioningSystemConfiguration", name = "WSGetVersioningSystemConfiguration", targetNamespace = "urn-com-amalto-xtentis-webservice")
        WSGetVersioningSystemConfiguration wsGetVersioningSystemConfiguration
    );

    @WebResult(name = "WSUniversePKArray", targetNamespace = "urn-com-amalto-xtentis-webservice", partName = "wsUniversePKArray")
    @WebMethod
    public WSUniversePKArray getUniversePKs(
        @WebParam(partName = "regex", name = "WSGetUniversePKs", targetNamespace = "urn-com-amalto-xtentis-webservice")
        WSGetUniversePKs regex
    );

    @WebResult(name = "WSString", targetNamespace = "urn-com-amalto-xtentis-webservice", partName = "wsBusinessConceptSchema")
    @WebMethod
    public WSString putBusinessConcept(
        @WebParam(partName = "wsPutBusinessConcept", name = "WSPutBusinessConcept", targetNamespace = "urn-com-amalto-xtentis-webservice")
        WSPutBusinessConcept wsPutBusinessConcept
    );

    @WebResult(name = "WSRoutingEngineV2Status", targetNamespace = "urn-com-amalto-xtentis-webservice", partName = "wsRoutingEngineStatus")
    @WebMethod
    public WSRoutingEngineV2Status routingEngineV2Action(
        @WebParam(partName = "wsRoutingEngineAction", name = "WSRoutingEngineV2Action", targetNamespace = "urn-com-amalto-xtentis-webservice")
        WSRoutingEngineV2Action wsRoutingEngineAction
    );

    @WebResult(name = "WSStringArray", targetNamespace = "urn-com-amalto-xtentis-webservice", partName = "wsStringArray")
    @WebMethod
    public WSStringArray runQuery(
        @WebParam(partName = "wsRunQuery", name = "WSRunQuery", targetNamespace = "urn-com-amalto-xtentis-webservice")
        WSRunQuery wsRunQuery
    );

    @WebResult(name = "WSBoolean", targetNamespace = "urn-com-amalto-xtentis-webservice", partName = "wsBoolean")
    @WebMethod
    public WSBoolean existsRoutingRule(
        @WebParam(partName = "wsExistsRoutingRule", name = "WSExistsRoutingRule", targetNamespace = "urn-com-amalto-xtentis-webservice")
        WSExistsRoutingRule wsExistsRoutingRule
    );

    @WebResult(name = "WSCheckServiceConfigResponse", targetNamespace = "urn-com-amalto-xtentis-webservice", partName = "result")
    @WebMethod
    public WSCheckServiceConfigResponse checkServiceConfiguration(
        @WebParam(partName = "serviceName", name = "WSCheckServiceConfigRequest", targetNamespace = "urn-com-amalto-xtentis-webservice")
        WSCheckServiceConfigRequest serviceName
    );

    @WebResult(name = "WSTransformerPK", targetNamespace = "urn-com-amalto-xtentis-webservice", partName = "wsTransformerPK")
    @WebMethod
    public WSTransformerPK deleteTransformer(
        @WebParam(partName = "wsTransformerDelete", name = "WSDeleteTransformer", targetNamespace = "urn-com-amalto-xtentis-webservice")
        WSDeleteTransformer wsTransformerDelete
    );

    @WebResult(name = "WSTransformerV2PK", targetNamespace = "urn-com-amalto-xtentis-webservice", partName = "wsTransformerV2PK")
    @WebMethod
    public WSTransformerV2PK putTransformerV2(
        @WebParam(partName = "wsTransformerV2", name = "WSPutTransformerV2", targetNamespace = "urn-com-amalto-xtentis-webservice")
        WSPutTransformerV2 wsTransformerV2
    );

    @WebResult(name = "WSItemPK", targetNamespace = "urn-com-amalto-xtentis-webservice", partName = "wsItemPK")
    @WebMethod
    public WSItemPK putItem(
        @WebParam(partName = "wsPutItem", name = "WSPutItem", targetNamespace = "urn-com-amalto-xtentis-webservice")
        WSPutItem wsPutItem
    );

    @WebResult(name = "WSDataModelPK", targetNamespace = "urn-com-amalto-xtentis-webservice", partName = "wsDataModelPK")
    @WebMethod
    public WSDataModelPK putDataModel(
        @WebParam(partName = "wsDataModel", name = "WSPutDataModel", targetNamespace = "urn-com-amalto-xtentis-webservice")
        WSPutDataModel wsDataModel
    );

    @WebResult(name = "WSSynchronizationItemPK", targetNamespace = "urn-com-amalto-xtentis-webservice", partName = "wsSynchronizationItemPK")
    @WebMethod
    public WSSynchronizationItemPK putSynchronizationItem(
        @WebParam(partName = "wsSynchronizationItem", name = "WSPutSynchronizationItem", targetNamespace = "urn-com-amalto-xtentis-webservice")
        WSPutSynchronizationItem wsSynchronizationItem
    );

    @WebResult(name = "WSString", targetNamespace = "urn-com-amalto-xtentis-webservice", partName = "wsString")
    @WebMethod
    public WSString synchronizationPutObjectXML(
        @WebParam(partName = "wsSynchronizationPutObjectXML", name = "WSSynchronizationPutObjectXML", targetNamespace = "urn-com-amalto-xtentis-webservice")
        WSSynchronizationPutObjectXML wsSynchronizationPutObjectXML
    );

    @WebResult(name = "WSString", targetNamespace = "urn-com-amalto-xtentis-webservice", partName = "wsErrors")
    @WebMethod
    public WSString checkSchema(
        @WebParam(partName = "wsSchema", name = "WSCheckSchema", targetNamespace = "urn-com-amalto-xtentis-webservice")
        WSCheckSchema wsSchema
    );

    @WebResult(name = "WSBackgroundJobPK", targetNamespace = "urn-com-amalto-xtentis-webservice", partName = "wsBackgroundJobPK")
    @WebMethod
    public WSBackgroundJobPK putBackgroundJob(
        @WebParam(partName = "wsPutBackgroundJob", name = "WSPutBackgroundJob", targetNamespace = "urn-com-amalto-xtentis-webservice")
        WSPutBackgroundJob wsPutBackgroundJob
    );

    @WebResult(name = "WSRole", targetNamespace = "urn-com-amalto-xtentis-webservice", partName = "wsRole")
    @WebMethod
    public WSRole getRole(
        @WebParam(partName = "wsGetRole", name = "WSGetRole", targetNamespace = "urn-com-amalto-xtentis-webservice")
        WSGetRole wsGetRole
    );

    @WebResult(name = "WSItemPKsByCriteriaResponse", targetNamespace = "urn-com-amalto-xtentis-webservice", partName = "wsItemPKsByCriteriaResponse")
    @WebMethod
    public WSItemPKsByCriteriaResponse getItemPKsByCriteria(
        @WebParam(partName = "wsGetItemPKsByCriteria", name = "WSGetItemPKsByCriteria", targetNamespace = "urn-com-amalto-xtentis-webservice")
        WSGetItemPKsByCriteria wsGetItemPKsByCriteria
    );

    @WebResult(name = "WSRoutingRulePKArray", targetNamespace = "urn-com-amalto-xtentis-webservice", partName = "wsRoutingRulePKs")
    @WebMethod
    public WSRoutingRulePKArray getRoutingRulePKs(
        @WebParam(partName = "regexp", name = "WSGetRoutingRulePKs", targetNamespace = "urn-com-amalto-xtentis-webservice")
        WSGetRoutingRulePKs regexp
    );

    @WebResult(name = "WSBackgroundJobPKArray", targetNamespace = "urn-com-amalto-xtentis-webservice", partName = "wsJobs")
    @WebMethod
    public WSBackgroundJobPKArray findBackgroundJobPKs(
        @WebParam(partName = "status", name = "WSFindBackgroundJobPKs", targetNamespace = "urn-com-amalto-xtentis-webservice")
        WSFindBackgroundJobPKs status
    );

    @WebResult(name = "WSPipeline", targetNamespace = "urn-com-amalto-xtentis-webservice", partName = "wsPipeline")
    @WebMethod
    public WSPipeline extractUsingTransformerThruView(
        @WebParam(partName = "wsExtractUsingTransformerThruView", name = "WSExtractUsingTransformerThruView", targetNamespace = "urn-com-amalto-xtentis-webservice")
        WSExtractUsingTransformerThruView wsExtractUsingTransformerThruView
    );

    @WebResult(name = "WSString", targetNamespace = "urn-com-amalto-xtentis-webservice", partName = "wsString")
    @WebMethod
    public WSString synchronizationGetObjectXML(
        @WebParam(partName = "wsSynchronizationGetObjectXML", name = "WSSynchronizationGetObjectXML", targetNamespace = "urn-com-amalto-xtentis-webservice")
        WSSynchronizationGetObjectXML wsSynchronizationGetObjectXML
    );

    @WebResult(name = "WSBackgroundJobPK", targetNamespace = "urn-com-amalto-xtentis-webservice", partName = "wsBackgroundJobPK")
    @WebMethod
    public WSBackgroundJobPK versioningCommitItems(
        @WebParam(partName = "wsVersioningCommitItems", name = "WSVersioningCommitItems", targetNamespace = "urn-com-amalto-xtentis-webservice")
        WSVersioningCommitItems wsVersioningCommitItems
    );

    @WebResult(name = "WSString", targetNamespace = "urn-com-amalto-xtentis-webservice", partName = "wsString")
    @WebMethod
    public WSString synchronizationGetItemXML(
        @WebParam(partName = "wsSynchronizationGetItemXML", name = "WSSynchronizationGetItemXML", targetNamespace = "urn-com-amalto-xtentis-webservice")
        WSSynchronizationGetItemXML wsSynchronizationGetItemXML
    );

    @WebResult(name = "WSTransformerV2PK", targetNamespace = "urn-com-amalto-xtentis-webservice", partName = "wsTransformerV2PK")
    @WebMethod
    public WSTransformerV2PK deleteTransformerV2(
        @WebParam(partName = "wsDeleteTransformerV2", name = "WSDeleteTransformerV2", targetNamespace = "urn-com-amalto-xtentis-webservice")
        WSDeleteTransformerV2 wsDeleteTransformerV2
    );

    @WebResult(name = "WSStringArray", targetNamespace = "urn-com-amalto-xtentis-webservice", partName = "wsUniverseNames")
    @WebMethod
    public WSStringArray getObjectsForUniverses(
        @WebParam(partName = "regex", name = "WSGetObjectsForUniverses", targetNamespace = "urn-com-amalto-xtentis-webservice")
        WSGetObjectsForUniverses regex
    );
}
