/*
 * Generated by XDoclet - Do not edit!
 */
package com.amalto.core.plugin.base.route.ejb.local;

/**
 * Local home interface for RouteTransformerPlugin.
 * @xdoclet-generated at 18-11-09
 * @copyright The XDoclet Team
 * @author XDoclet
 * @version ${version}
 */
public interface RouteTransformerPluginLocalHome
   extends javax.ejb.EJBLocalHome
{
   public static final String COMP_NAME="java:comp/env/ejb/RouteTransformerPluginLocal";
   public static final String JNDI_NAME="amalto/local/transformer/plugin/route";

   public com.amalto.core.plugin.base.route.ejb.local.RouteTransformerPluginLocal create()
      throws javax.ejb.CreateException;

}
