/*
 * Generated by XDoclet - Do not edit!
 */
package com.amalto.service.dumptoconsole.ejb.local;

/**
 * Local home interface for DumpToConsole.
 * @xdoclet-generated at 3-08-09
 * @copyright The XDoclet Team
 * @author XDoclet
 * @version ${version}
 */
public interface DumpToConsoleLocalHome
   extends javax.ejb.EJBLocalHome
{
   public static final String COMP_NAME="java:comp/env/ejb/DumpToConsoleLocal";
   public static final String JNDI_NAME="amalto/local/service/dumptoconsole";

   public com.amalto.service.dumptoconsole.ejb.local.DumpToConsoleLocal create()
      throws javax.ejb.CreateException;

}
