// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.2_01, construire R40)
// Generated source version: 1.1.2

package talend.core.transformer.plugin.v2.tiscall.webservices;


public class ArrayOf_xsd_string {
    protected java.lang.String[] item;
    
    public ArrayOf_xsd_string() {
    }
    
    public ArrayOf_xsd_string(java.lang.String[] item) {
        this.item = item;
    }
    
    public java.lang.String[] getItem() {
        return item;
    }
    
    public void setItem(java.lang.String[] item) {
        this.item = item;
    }
}
