// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.2_01, construire R40)
// Generated source version: 1.1.2

package talend.core.transformer.plugin.v2.tiscall.webservices;


public class RunJobReturn {
    protected talend.core.transformer.plugin.v2.tiscall.webservices.ArrayOf_xsd_string[] item;
    
    public RunJobReturn() {
    }
    
    public RunJobReturn(talend.core.transformer.plugin.v2.tiscall.webservices.ArrayOf_xsd_string[] item) {
        this.item = item;
    }
    
    public talend.core.transformer.plugin.v2.tiscall.webservices.ArrayOf_xsd_string[] getItem() {
        return item;
    }
    
    public void setItem(talend.core.transformer.plugin.v2.tiscall.webservices.ArrayOf_xsd_string[] item) {
        this.item = item;
    }
}
