/*
 * Generated by XDoclet - Do not edit!
 */
package com.amalto.core.plugin.base.codec.ejb.local;

/**
 * Local home interface for CodecPlugin.
 * @xdoclet-generated at 18-11-09
 * @copyright The XDoclet Team
 * @author XDoclet
 * @version ${version}
 */
public interface CodecPluginLocalHome
   extends javax.ejb.EJBLocalHome
{
   public static final String COMP_NAME="java:comp/env/ejb/CodecPluginLocal";
   public static final String JNDI_NAME="amalto/local/transformer/plugin/codec";

   public com.amalto.core.plugin.base.codec.ejb.local.CodecPluginLocal create()
      throws javax.ejb.CreateException;

}
